// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5v2Gu-Hiw8rsLNi1t1AWrPveyhEP8pEA',
    appId: '1:455474853473:web:40bca9eecc77adc5b9dc20',
    messagingSenderId: '455474853473',
    projectId: 'smartkisan-b2edf',
    authDomain: 'smartkisan-b2edf.firebaseapp.com',
    storageBucket: 'smartkisan-b2edf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCElIhxr05TRZLEImCpEJ-5tKuxWloA8WY',
    appId: '1:455474853473:android:8923532f4b219ab0b9dc20',
    messagingSenderId: '455474853473',
    projectId: 'smartkisan-b2edf',
    storageBucket: 'smartkisan-b2edf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdD2TmQPECqWLAlaCvkjSbh97FUVFlDqQ',
    appId: '1:455474853473:ios:d4c9cd2ba1a8e9d7b9dc20',
    messagingSenderId: '455474853473',
    projectId: 'smartkisan-b2edf',
    storageBucket: 'smartkisan-b2edf.firebasestorage.app',
    iosBundleId: 'com.example.smartKisan',
  );
}
