// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// [DefaultFirebaseOptions] provides the platform-specific configuration options 
/// required to initialize the Firebase SDK in this application.
/// 
/// Note: This class is auto-generated by the FlutterFire CLI. During a viva, 
/// you can explain that this file acts as a router, supplying the correct API keys 
/// depending on whether the app is running on Android, iOS, or Web.
class DefaultFirebaseOptions {
  /// Purpose: Determines the current operating system/platform at runtime and returns the corresponding Firebase configuration.
  /// Inputs: None (reads system environment variables via [defaultTargetPlatform]).
  /// Outputs: A [FirebaseOptions] object containing the correct API keys for the active platform.
  static FirebaseOptions get currentPlatform {
    // 1. Check if the application is currently running in a web browser.
    if (kIsWeb) {
      return web;
    }
    // 2. If not web, check the specific native OS.
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        // Returns the Android-specific Firebase configuration defined below.
        return android;
      case TargetPlatform.iOS:
        // Returns the iOS-specific Firebase configuration defined below.
        return ios;
      case TargetPlatform.macOS:
        // Throws an error because macOS Firebase setup was not configured during the FlutterFire init.
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // --- Platform Specific Configurations ---
  // These objects hold the raw API keys, App IDs, and Project IDs required to securely connect to the Firebase backend.
  
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5v2Gu-Hiw8rsLNi1t1AWrPveyhEP8pEA',
    appId: '1:455474853473:web:40bca9eecc77adc5b9dc20',
    messagingSenderId: '455474853473',
    projectId: 'smartkisan-b2edf',
    authDomain: 'smartkisan-b2edf.firebaseapp.com',
    storageBucket: 'smartkisan-b2edf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCElIhxr05TRZLEImCpEJ-5tKuxWloA8WY',
    appId: '1:455474853473:android:8923532f4b219ab0b9dc20',
    messagingSenderId: '455474853473',
    projectId: 'smartkisan-b2edf',
    storageBucket: 'smartkisan-b2edf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdD2TmQPECqWLAlaCvkjSbh97FUVFlDqQ',
    appId: '1:455474853473:ios:d4c9cd2ba1a8e9d7b9dc20',
    messagingSenderId: '455474853473',
    projectId: 'smartkisan-b2edf',
    storageBucket: 'smartkisan-b2edf.appspot.com',
    iosBundleId: 'com.example.smartKisan',
  );
}
