import 'package:flutter/material.dart';

class LocalizationService {
  static const String EN = 'EN';
  static const String HI = 'HI';
  static const String NE = 'NE';

  // Global language state (singleton pattern)
  static String _currentLanguage = EN;

  static String get currentLanguage => _currentLanguage;

  static void setLanguage(String languageCode) {
    _currentLanguage = languageCode;
  }

  static final Map<String, Map<String, String>> _translations = {
    EN: {
      // Welcome & Onboarding
      'smart_kisan': 'Smart Kisan',
      'empowering_farmers': 'Empowering Farmers with Smart Solutions',
      'get_updates': 'Get real-time Weather updates, Crop advice, Pest & Diseases Help and Water optimizations at your fingertips.',
      'get_started': 'Get Started',
      'log_in': 'Log In',
      'choose_language': 'Choose Your Language',
      'skip': 'Skip',
      'back': 'Back',
      'next': 'Next',
      'English': 'English',
      'Hindi': 'Hindi',
      'Nepali': 'Nepali',
      'Monitoring soil and plant': 'Monitoring soil and plant',
      'We aim to use optical (VIR) sensing to observe the fields and make timely crop management decisions.': 'We aim to use optical (VIR) sensing to observe the fields and make timely crop management decisions.',
      'Crop Selection': 'Crop Selection',
      'Our project can use AI & Machine learning to select the best crop according to the land and water resources.': 'Our project can use AI & Machine learning to select the best crop according to the land and water resources.',
      'Improve agriculture precision': 'Improve agriculture precision',
      'We will use satellite imagery, image processing, deep learning, computer vision, and remote sensing to detect changes in the field and crops and solve the problems whenever they pop.': 'We will use satellite imagery, image processing, deep learning, computer vision, and remote sensing to detect changes in the field and crops and solve the problems whenever they pop.',
      
      // Login & Registration
      'Email': 'Email',
      'Password': 'Password',
      'Sign In': 'Sign In',
      'Don\'t have an account? Sign Up': 'Don\'t have an account? Sign Up',
      'Forgot Password?': 'Forgot Password?',
      'Remember Me': 'Remember Me',
      'Sign Up': 'Sign Up',
      'Create Account': 'Create Account',
      'Confirm Password': 'Confirm Password',
      'Already have an account? Sign In': 'Already have an account? Sign In',
      'please Log in to continue': 'please Log in to continue',
      'enter_email': 'Enter your email',
      'enter_password': 'Enter your password',
      'Please enter your email': 'Please enter your email',
      'Please enter your password': 'Please enter your password',
      'Log in': 'Log in',
      'or sign in with': 'or sign in with',
      'Google Sign-In failed or cancelled': 'Google Sign-In failed or cancelled',
      'Forgot Password': 'Forgot Password',
      'Enter the email address you used when you joined and we\'ll send you instructions to reset your password.': 'Enter the email address you used when you joined and we\'ll send you instructions to reset your password.',
      'Email ID': 'Email ID',
      'Please enter email id': 'Please enter email id',
      'Please enter a valid email id': 'Please enter a valid email id',
      'Enter email id': 'Enter email id',
      'Send Link/Code': 'Send Link/Code',
      'Having a Problem?': 'Having a Problem?',
      'Send Again': 'Send Again',
      'Verify code sent': 'Verify code sent',
      'Enter 4-digits code sent to you at': 'Enter 4-digits code sent to you at',
      'Verify Code': 'Verify Code',
      'New Password': 'New Password',
      'Confirm New Password': 'Confirm New Password',
      'Enter New Password': 'Enter New Password',
      'Please enter new password': 'Please enter new password',
      'Enter new password': 'Enter new password',
      'Please confirm new password': 'Please confirm new password',
      'Passwords do not match': 'Passwords do not match',
      'Confirm new password': 'Confirm new password',
      'Create New Password': 'Create New Password',
      'Congratulations!': 'Congratulations!',
      'A password reset link has been sent to your email. Please check your inbox (and spam), click the link to reset your password, and then login here.': 'A password reset link has been sent to your email. Please check your inbox (and spam), click the link to reset your password, and then login here.',
      'create an account to continue': 'create an account to continue',
      'First Name': 'First Name',
      'Please enter your first name': 'Please enter your first name',
      'Enter your first name': 'Enter your first name',
      'Last Name': 'Last Name',
      'Please enter your last name': 'Please enter your last name',
      'Enter your last name': 'Enter your last name',
      'Mobile Number': 'Mobile Number',
      'Please enter your mobile number': 'Please enter your mobile number',
      'Enter your mobile number': 'Enter your mobile number',
      'Please enter a valid mobile number (10-15 digits)': 'Please enter a valid mobile number (10-15 digits)',
      'Please enter a valid email address': 'Please enter a valid email address',
      'Password must be at least 6 characters': 'Password must be at least 6 characters',
      'This email is already in use. Please log in instead.': 'This email is already in use. Please log in instead.',
      'The email address is invalid.': 'The email address is invalid.',
      'The password is too weak.': 'The password is too weak.',
      'An unexpected error occurred. Please try again.': 'An unexpected error occurred. Please try again.',
      'Already have an account?': 'Already have an account?',
      'sign up': 'sign up',
      'or sign up with': 'or sign up with',
      'Security Fingerprint': 'Security Fingerprint',
      'Scan your fingerprint to login': 'Scan your fingerprint to login',
      'Use fingerprint to access': 'Use fingerprint to access',
      'Tap the icon above to scan.': 'Tap the icon above to scan.',
      'Tap to login with Fingerprint': 'Tap to login with Fingerprint',
      'Use Passcode': 'Use Passcode',
      'Passcode': 'Passcode',
      'Enter PassCode': 'Enter PassCode',
      'Submit': 'Submit',
      'Forgot Passcode? Login with Email': 'Forgot Passcode? Login with Email',
      'Incorrect passcode. Try 1234.': 'Incorrect passcode. Try 1234.',
      'Welcome back!': 'Welcome back!',
      'Session expired. Login with Email first.': 'Session expired. Login with Email first.',
      'Fingerprint login is only available on Mobile Apps.': 'Fingerprint login is only available on Mobile Apps.',
      'Fingerprint not supported on this device': 'Fingerprint not supported on this device',
      'Session expired. Please login with Password first.': 'Session expired. Please login with Password first.',
      
      // Home Page
      'Good morning': 'Good morning',
      'Locating...': 'Locating...',
      'Current Weather': 'Current Weather',
      'Humidity': 'Humidity',
      'Wind': 'Wind',
      'Visibility': 'Visibility',
      'Feels Like': 'Feels Like',
      'Farm Overview': 'Farm Overview',
      'Crop Advisory': 'Crop Advisory',
      'Pest & Disease Help': 'Pest & Disease Help',
      'Water Optimization': 'Water Optimization',
      'Weather Forecast': 'Weather Forecast',
      'Active Crops': 'Active Crops',
      'Tap to add crops': 'Tap to add crops',
      'Rice, Wheat, Corn': 'Rice, Wheat, Corn',
      'Yield Rate': 'Yield Rate',
      'Start farming to see': 'Start farming to see',
      '+5% from last season': '+5% from last season',
      'Alerts': 'Alerts',
      'No alerts yet': 'No alerts yet',
      'Pest warning, Rain': 'Pest warning, Rain',
      'Tasks Done': 'Tasks Done',
      'This week': 'This week',
      'Setup your farm': 'Setup your farm',
      'Language / भाषा': 'Language / भाषा',
      'Currently: English': 'Currently: English',
      'नेपाली': 'नेपाली',
      'Recent Activity': 'Recent Activity',
      'Welcome to Smart Kisan!': 'Welcome to Smart Kisan!',
      'Just now': 'Just now',
      'Complete farm setup to get started': 'Complete farm setup to get started',
      '1 minute ago': '1 minute ago',
      'Pest identified in tomato crop': 'Pest identified in tomato crop',
      '2 hours ago': '2 hours ago',
      'Weather alert: Rain expected': 'Weather alert: Rain expected',
      '5 hours ago': '5 hours ago',
      'Home': 'Home',
      'Ask AI': 'Ask AI',
      'Scan': 'Scan',
      'Add\nLocation': 'Add\nLocation',
      'EN': 'EN',
      
      // Water Optimization
      'water_optimization': 'Water Optimization',
      'land_area': 'Land Area',
      'crop_type': 'Crop Type',
      'soil_type': 'Soil Type',
      'calculate': 'Calculate Water Need',
      'weather': 'Weather Status',
      'history': 'Calculation History',
      'no_data': 'No calculations yet',
      'enter_area': 'Please enter land area',
      'enter_crop': 'Please enter crop name',
      'water_needed': 'Water Needed',
      'daily_water': 'Daily Water',
      'Total Water Required': 'Total Water Required',
      'Growing Days': 'Growing Days',
      'Recommendation': 'Recommendation',
      'Invalid crop name. Please enter a real agricultural crop.': 'Invalid crop name. Please enter a real agricultural crop.',
      'Enter area': 'Enter area',
      'Enter any crop (e.g., wheat, tomato, rice)': 'Enter any crop (e.g., wheat, tomato, rice)',
      'Water Recommendation': 'Water Recommendation',
      'Weather check done': 'Weather check done',
      'Liters': 'Liters',
      'L/day': 'L/day',
      'Growing Season': 'Growing Season',
      'days': 'days',
      'AI Recommendation': 'AI Recommendation',
      'Close': 'Close',
      
      // Weather
      'Current Conditions': 'Current Conditions',
      'Today': 'Today',
      'Hourly Forecast': 'Hourly Forecast',
      'Now': 'Now',
      '+1h': '+1h',
      '+2h': '+2h',
      '+3h': '+3h',
      '+4h': '+4h',
      '+5h': '+5h',
      '7-Day Forecast': '7-Day Forecast',
      'Tomorrow': 'Tomorrow',
      'Partly Cloudy': 'Partly Cloudy',
      'Rain': 'Rain',
      'Wednesday': 'Wednesday',
      'Cloudy': 'Cloudy',
      'Thursday': 'Thursday',
      'Friday': 'Friday',
      'Sunny': 'Sunny',
      'Saturday': 'Saturday',
      'Sunday': 'Sunday',
      'Farming Advice': 'Farming Advice',
      'Conditions are stable. No specific warnings.': 'Conditions are stable. No specific warnings.',
      'Rain Detected': 'Rain Detected',
      'Avoid applying fertilizers or pesticides to prevent runoff.': 'Avoid applying fertilizers or pesticides to prevent runoff.',
      'Irrigation Needed': 'Irrigation Needed',
      'High temperatures detected. Water crops to prevent heat stress.': 'High temperatures detected. Water crops to prevent heat stress.',
      'High Winds': 'High Winds',
      'Avoid spraying pesticides as drift may occur.': 'Avoid spraying pesticides as drift may occur.',
      'Good Field Conditions': 'Good Field Conditions',
      'Ideal weather for sowing, harvesting, or equipment maintenance.': 'Ideal weather for sowing, harvesting, or equipment maintenance.',
      'Safety Warning': 'Safety Warning',
      'Lightning risk. Stay away from open fields and metal equipment.': 'Lightning risk. Stay away from open fields and metal equipment.',
      'Cold Stress Risk': 'Cold Stress Risk',
      'Temperatures are low. Protect sensitive seedlings from frost.': 'Temperatures are low. Protect sensitive seedlings from frost.',
      'Stable Conditions': 'Stable Conditions',
      'Weather is normal. Continue routine farm operations.': 'Weather is normal. Continue routine farm operations.',
      'Storm Alert': 'Storm Alert',
      'Thunderstorm activity detected. Halt all field work immediately.': 'Thunderstorm activity detected. Halt all field work immediately.',
      'Heavy Rain Alert': 'Heavy Rain Alert',
      'Heavy precipitation expected. Ensure drainage systems are clear.': 'Heavy precipitation expected. Ensure drainage systems are clear.',
      'Gale Warning': 'Gale Warning',
      'Damaging winds detected. Secure loose structures and livestock.': 'Damaging winds detected. Secure loose structures and livestock.',
      'Select Location': 'Select Location',
      'Use Current GPS': 'Use Current GPS',
      
      // Settings
      'Settings': 'Settings',
      'Manage your account and preferences': 'Manage your account and preferences',
      'Profile Settings': 'Profile Settings',
      'Manage your personal information': 'Manage your personal information',
      'Ramesh Kumar': 'Ramesh Kumar',
      'Kumar Organic Farm': 'Kumar Organic Farm',
      'Edit Profile': 'Edit Profile',
      'Notification Settings': 'Notification Settings',
      'Manage your alerts and notifications': 'Manage your alerts and notifications',
      'Active Notifications': 'Active Notifications',
      'You have 7 notifications enabled': 'You have 7 notifications enabled',
      'You have {count} notifications enabled': 'You have {count} notifications enabled',
      '7/9': '7/9',
      'Manage Notifications': 'Manage Notifications',
      'Language': 'Language',
      'Select your preferred language': 'Select your preferred language',
      'Theme': 'Theme',
      'Choose your display theme': 'Choose your display theme',
      'Light Mode': 'Light Mode',
      'Dark Mode': 'Dark Mode',
      'Auto Mode': 'Auto Mode',
      'Units of Measurement': 'Units of Measurement',
      'Set your preferred units': 'Set your preferred units',
      'Temperature': 'Temperature',
      'Celsius (°C)': 'Celsius (°C)',
      'Fahrenheit (°F)': 'Fahrenheit (°F)',
      'Area': 'Area',
      'Acres': 'Acres',
      'Hectares': 'Hectares',
      'Volume': 'Volume',
      'Gallons': 'Gallons',
      'Privacy & Security': 'Privacy & Security',
      'Manage your privacy settings': 'Manage your privacy settings',
      'Share Usage Data': 'Share Usage Data',
      'Help improve the app': 'Help improve the app',
      'Analytics': 'Analytics',
      'Allow analytics tracking': 'Allow analytics tracking',
      'Location Tracking': 'Location Tracking',
      'For weather and field data': 'For weather and field data',
      'Change Password': 'Change Password',
      'Two-Factor Authentication': 'Two-Factor Authentication',
      'About': 'About',
      'App information and version': 'App information and version',
      'Smart Kisan App': 'Smart Kisan App',
      'Version 1.0.0': 'Version 1.0.0',
      '© 2024 Smart Kisan. All rights reserved.': '© 2024 Smart Kisan. All rights reserved.',
      'Logout': 'Logout',
      'Are you sure you want to logout?': 'Are you sure you want to logout?',
      'Cancel': 'Cancel',
      'Change Photo': 'Change Photo',
      'Full Name': 'Full Name',
      'Farm Name': 'Farm Name',
      'Phone Number': 'Phone Number',
      'Location': 'Location',
      'Save Changes': 'Save Changes',
      'Profile updated successfully!': 'Profile updated successfully!',
      'Old Password': 'Old Password',
      'Password Requirements:': 'Password Requirements:',
      'At least 6 characters': 'At least 6 characters',
      'Contains uppercase and lowercase letters': 'Contains uppercase and lowercase letters',
      'Contains at least one number': 'Contains at least one number',
      'Contains at least one special character': 'Contains at least one special character',
      'Password changed successfully!': 'Password changed successfully!',
      'Weather Alerts': 'Weather Alerts',
      'Get notified about weather changes, rain forecasts, and temperature alerts': 'Get notified about weather changes, rain forecasts, and temperature alerts',
      'Pest & Disease Alerts': 'Pest & Disease Alerts',
      'Important pest detection notifications and disease outbreak warnings': 'Important pest detection notifications and disease outbreak warnings',
      'Irrigation Reminders': 'Irrigation Reminders',
      'Scheduled irrigation notifications and soil moisture alerts': 'Scheduled irrigation notifications and soil moisture alerts',
      'Crop Health Updates': 'Crop Health Updates',
      'Monitor your crop health status and growth stage updates': 'Monitor your crop health status and growth stage updates',
      'Market Prices': 'Market Prices',
      'Stay updated on crop prices and market trends': 'Stay updated on crop prices and market trends',
      'General Updates': 'General Updates',
      'App updates, farming tips, and seasonal recommendations': 'App updates, farming tips, and seasonal recommendations',
      'Email Notifications': 'Email Notifications',
      'Receive alerts and updates via email': 'Receive alerts and updates via email',
      'Push Notifications': 'Push Notifications',
      'In-app and mobile push notifications': 'In-app and mobile push notifications',
      'SMS Notifications': 'SMS Notifications',
      'Receive critical alerts via text message': 'Receive critical alerts via text message',
      'Enable All': 'Enable All',
      'Disable All': 'Disable All',
      'About Notifications': 'About Notifications',
      'We recommend keeping critical alerts like weather and pest notifications enabled to stay informed about important farming conditions.': 'We recommend keeping critical alerts like weather and pest notifications enabled to stay informed about important farming conditions.',
      
      // Crop Advisory
      'Manage fields & get recommendations': 'Manage fields & get recommendations',
      'Your Fields': 'Your Fields',
      'Add Field': 'Add Field',
      'Crops in': 'Crops in',
      'Add Crop': 'Add Crop',
      'No fields added yet. Add one to start tracking.': 'No fields added yet. Add one to start tracking.',
      'No crops added yet': 'No crops added yet',
      'Get Smart AI Recommendations': 'Get Smart AI Recommendations',
      'Winter Season (Nov-Feb)': 'Winter Season (Nov-Feb)',
      'Reduce watering frequency.': 'Reduce watering frequency.',
      'Protect sensitive crops from frost.': 'Protect sensitive crops from frost.',
      'Plant cover crops for soil health.': 'Plant cover crops for soil health.',
      'Spring Season (Mar-May)': 'Spring Season (Mar-May)',
      'Prepare land for planting.': 'Prepare land for planting.',
      'Watch for aphids.': 'Watch for aphids.',
      'Clean irrigation channels.': 'Clean irrigation channels.',
      'Monsoon Season (Jun-Sep)': 'Monsoon Season (Jun-Sep)',
      'Ensure drainage to prevent waterlogging.': 'Ensure drainage to prevent waterlogging.',
      'Monitor for stem borer.': 'Monitor for stem borer.',
      'Harvest rainwater.': 'Harvest rainwater.',
      'Autumn Season (Oct)': 'Autumn Season (Oct)',
      'Harvest monsoon crops.': 'Harvest monsoon crops.',
      'Prepare soil for wheat.': 'Prepare soil for wheat.',
      'Store grains in dry places.': 'Store grains in dry places.',
      'Seasonal Tips': 'Seasonal Tips',
      'Add New Field': 'Add New Field',
      'Field Name': 'Field Name',
      'e.g., South Field': 'e.g., South Field',
      'Size': 'Size',
      'e.g., 2 Acres / 5 Katha': 'e.g., 2 Acres / 5 Katha',
      'Soil Type': 'Soil Type',
      'Loamy Soil': 'Loamy Soil',
      'Clay Soil': 'Clay Soil',
      'Sandy Soil': 'Sandy Soil',
      'Silt Soil': 'Silt Soil',
      'Peaty Soil': 'Peaty Soil',
      'Chalky Soil': 'Chalky Soil',
      'Black Soil': 'Black Soil',
      'Save': 'Save',
      'Wait 2 seconds before adding another field': 'Wait 2 seconds before adding another field',
      'Max 10 fields allowed per account': 'Max 10 fields allowed per account',
      'Error:': 'Error:',
      'Custom Crop Name': 'Custom Crop Name',
      'Enter Name': 'Enter Name',
      'Add Custom Crop': 'Add Custom Crop',
      'Or Select Common Crop:': 'Or Select Common Crop:',
      'Rice (Paddy)': 'Rice (Paddy)',
      'Monsoon': 'Monsoon',
      '100-150 days': '100-150 days',
      'High': 'High',
      'Wheat': 'Wheat',
      'Winter': 'Winter',
      '110-130 days': '110-130 days',
      'Medium': 'Medium',
      'Maize (Corn)': 'Maize (Corn)',
      'Spring/Summer': 'Spring/Summer',
      '90-110 days': '90-110 days',
      'Millet (Kodo)': 'Millet (Kodo)',
      'Summer': 'Summer',
      '100-120 days': '100-120 days',
      'Low': 'Low',
      'Barley (Jau)': 'Barley (Jau)',
      'Buckwheat (Phapar)': 'Buckwheat (Phapar)',
      'Autumn': 'Autumn',
      '70-90 days': '70-90 days',
      'Potato': 'Potato',
      '90-120 days': '90-120 days',
      'Tomato': 'Tomato',
      'All Year': 'All Year',
      '90-100 days': '90-100 days',
      'Cauliflower': 'Cauliflower',
      '80-100 days': '80-100 days',
      'Cabbage': 'Cabbage',
      'Onion': 'Onion',
      '120-150 days': '120-150 days',
      'Garlic': 'Garlic',
      '130-160 days': '130-160 days',
      'Ginger': 'Ginger',
      '240-270 days': '240-270 days',
      'Radish': 'Radish',
      '40-60 days': '40-60 days',
      'Carrot': 'Carrot',
      'Brinjal (Eggplant)': 'Brinjal (Eggplant)',
      'Okra (Lady Finger)': 'Okra (Lady Finger)',
      '60-90 days': '60-90 days',
      'Spinach (Saag)': 'Spinach (Saag)',
      '30-45 days': '30-45 days',
      'Cucumber': 'Cucumber',
      '60-80 days': '60-80 days',
      'Pumpkin': 'Pumpkin',
      'Bitter Gourd (Karela)': 'Bitter Gourd (Karela)',
      'Bottle Gourd (Lauka)': 'Bottle Gourd (Lauka)',
      'Chili': 'Chili',
      'Peas': 'Peas',
      'Broad Bean (Bakulla)': 'Broad Bean (Bakulla)',
      'Lentil (Musuro)': 'Lentil (Musuro)',
      'Chickpea (Chana)': 'Chickpea (Chana)',
      'Black Gram (Mas)': 'Black Gram (Mas)',
      'Soybean': 'Soybean',
      'Pigeon Pea (Rahar)': 'Pigeon Pea (Rahar)',
      '150-180 days': '150-180 days',
      'Mung Bean': 'Mung Bean',
      'Mustard': 'Mustard',
      'Sugarcane': 'Sugarcane',
      'Spring': 'Spring',
      '300-365 days': '300-365 days',
      'Tea': 'Tea',
      'Perennial': 'Perennial',
      'Years': 'Years',
      'Coffee': 'Coffee',
      'Cardamom (Alaichi)': 'Cardamom (Alaichi)',
      'Jute': 'Jute',
      'Sunflower': 'Sunflower',
      'Groundnut (Peanut)': 'Groundnut (Peanut)',
      'Turmeric': 'Turmeric',
      'Banana': 'Banana',
      '12-14 months': '12-14 months',
      'Mango': 'Mango',
      'Apple': 'Apple',
      'Orange/Citrus': 'Orange/Citrus',
      'Papaya': 'Papaya',
      '9-12 months': '9-12 months',
      'Guava': 'Guava',
      'Lychee': 'Lychee',
      'Watermelon': 'Watermelon',
      'Max 20 crops per field allowed': 'Max 20 crops per field allowed',
      'Delete Field?': 'Delete Field?',
      'This will delete the field and all crops inside it.': 'This will delete the field and all crops inside it.',
      'Delete': 'Delete',
      'AI Recommendations': 'AI Recommendations',
      'Suggested Crops (tap + to add):': 'Suggested Crops (tap + to add):',
      'Added': 'Added',
      'to field': 'to field',
      'Edit': 'Edit',
      
      // Pest & Disease Help
      'Early detection and treatment guidance': 'Early detection and treatment guidance',
      'Scan Your Crop': 'Scan Your Crop',
      'Use your camera to identify pests and diseases': 'Use your camera to identify pests and diseases',
      'Scan Now': 'Scan Now',
      'Active Alerts': 'Active Alerts',
      'No active alerts. Your crops are looking healthy!': 'No active alerts. Your crops are looking healthy!',
      'Treatment:': 'Treatment:',
      'Detected:': 'Detected:',
      'Recent Scans': 'Recent Scans',
      'No scans yet. Start by scanning a crop!': 'No scans yet. Start by scanning a crop!',
      'Prevention Tips': 'Prevention Tips',
      'Regular field inspections to catch issues early': 'Regular field inspections to catch issues early',
      'Crop rotation to prevent pest buildup': 'Crop rotation to prevent pest buildup',
      'Maintain proper plant spacing for air circulation': 'Maintain proper plant spacing for air circulation',
      'Remove plant debris to reduce disease habitat': 'Remove plant debris to reduce disease habitat',
      'Use disease-resistant crop varieties when available': 'Use disease-resistant crop varieties when available',
      'Search Knowledge Base': 'Search Knowledge Base',
      'Find information about pests and diseases': 'Find information about pests and diseases',
      'Search': 'Search',
      'This feature will open your camera to scan crops for pests and diseases.': 'This feature will open your camera to scan crops for pests and diseases.',
      'Make sure to:': 'Make sure to:',
      '1. Focus on the affected area': '1. Focus on the affected area',
      '2. Use good lighting': '2. Use good lighting',
      '3. Keep camera steady': '3. Keep camera steady',
      'Open Camera': 'Open Camera',
      'Analyzing crop image...': 'Analyzing crop image...',
      'Scan Results': 'Scan Results',
      'Crop:': 'Crop:',
      'Unknown': 'Unknown',
      'Status:': 'Status:',
      'Confidence:': 'Confidence:',
      '%': '%',
      'Save Result': 'Save Result',
      'Scan saved to history': 'Scan saved to history',
      'Mark Resolved': 'Mark Resolved',
      'Alert marked as resolved': 'Alert marked as resolved',
      'Enter keywords like "aphids", "leaf blight", "corn diseases", etc.': 'Enter keywords like "aphids", "leaf blight", "corn diseases", etc.',
      'Search for': 'Search for',
      'Fetching information...': 'Fetching information...',
      'Information about': 'Information about',
      'No information found. Please try another search.': 'No information found. Please try another search.',
      
      // Scan Page
      'AI-powered disease & pest detection': 'AI-powered disease & pest detection',
      '24': '24',
      'Total Scans': 'Total Scans',
      '18': '18',
      'Healthy': 'Healthy',
      '6': '6',
      'Issues Found': 'Issues Found',
      'Start New Scan': 'Start New Scan',
      'Take Photo': 'Take Photo',
      'Use camera': 'Use camera',
      'Upload Image': 'Upload Image',
      'From gallery': 'From gallery',
      'How to get best results': 'How to get best results',
      '• Take clear, well-lit photos': '• Take clear, well-lit photos',
      '• Focus on affected areas': '• Focus on affected areas',
      '• Include whole leaf when possible': '• Include whole leaf when possible',
      '• Avoid blurry or dark images': '• Avoid blurry or dark images',
      'No scans yet': 'No scans yet',
      'Start by taking a photo or uploading an image': 'Start by taking a photo or uploading an image',
      'Camera Access': 'Camera Access',
      'This feature will open the camera for scanning in the next phase.': 'This feature will open the camera for scanning in the next phase.',
      'You can take photos of crops for disease detection.': 'You can take photos of crops for disease detection.',
      'This feature will open the gallery for image selection in the next phase.': 'This feature will open the gallery for image selection in the next phase.',
      'You can upload crop photos for analysis.': 'You can upload crop photos for analysis.',
      'Choose Image': 'Choose Image',
      'Scan Details': 'Scan Details',
      'View Details →': 'View Details →',
      
      // Location Page
      'My Locations': 'My Locations',
      'Manage your farm fields': 'Manage your farm fields',
      'Current Location': 'Current Location',
      'Kathmandu, Nepal': 'Kathmandu, Nepal',
      'Update': 'Update',
      'Map View': 'Map View',
      'Showing all your fields': 'Showing all your fields',
      'Saved Fields': 'Saved Fields',
      'Main Rice Field': 'Main Rice Field',
      'Primary': 'Primary',
      '2.5 acres': '2.5 acres',
      '27.7172° N, 85.3240° E': '27.7172° N, 85.3240° E',
      'North Wheat Field': 'North Wheat Field',
      '1.8 acres': '1.8 acres',
      '27.7185° N, 85.3255° E': '27.7185° N, 85.3255° E',
      'South Corn Field': 'South Corn Field',
      '3.2 acres': '3.2 acres',
      'Corn, Vegetables': 'Corn, Vegetables',
      '27.7160° N, 85.3230° E': '27.7160° N, 85.3230° E',
      'Overview': 'Overview',
      '3': '3',
      'Total Fields': 'Total Fields',
      '7.5': '7.5',
      'Total Area': 'Total Area',
      'acres': 'acres',
      '4': '4',
      'Crop Types': 'Crop Types',
      'Location-Based Insights': 'Location-Based Insights',
      'Get weather forecasts, soil recommendations, and alerts specific to each field location.': 'Get weather forecasts, soil recommendations, and alerts specific to each field location.',
      'This feature will access your current location or allow you to search for a new location in the next phase.': 'This feature will access your current location or allow you to search for a new location in the next phase.',
      'This feature will allow you to add a new farm field with location, size, and crop information in the next phase.': 'This feature will allow you to add a new farm field with location, size, and crop information in the next phase.',
      'Editing': 'Editing',
      'Delete Field': 'Delete Field',
      'Are you sure you want to delete': 'Are you sure you want to delete',
      'Navigate to Field': 'Navigate to Field',
      'Opening navigation to': 'Opening navigation to',
      'at coordinates': 'at coordinates',
      'This will open your preferred map app in the next phase.': 'This will open your preferred map app in the next phase.',
      'Field Details': 'Field Details',
      'Name:': 'Name:',
      'Area:': 'Area:',
      'Active Crops:': 'Active Crops:',
      'Coordinates:': 'Coordinates:',
      'Navigate': 'Navigate',
      'View Details': 'View Details',
      
      // AI Chat
      'Smart Kisan AI': 'Smart Kisan AI',
      'Your Expert Assistant': 'Your Expert Assistant',
      'Quick Questions:': 'Quick Questions:',
      'Best fertilizer for rice?': 'Best fertilizer for rice?',
      'Identify this pest': 'Identify this pest',
      'Irrigation for wheat?': 'Irrigation for wheat?',
      'Tomorrow\'s weather?': 'Tomorrow\'s weather?',
      'Start chatting with Smart Kisan': 'Start chatting with Smart Kisan',
      'Ask about farming...': 'Ask about farming...',
      
      // Notifications
      'Notifications': 'Notifications',
      'unread notifications': 'unread notifications',
      'Filter': 'Filter',
      'Mark all read': 'Mark all read',
      'Clear all': 'Clear all',
      'Filter Notifications': 'Filter Notifications',
      'All': 'All',
      'Unread': 'Unread',
      'Weather': 'Weather',
      'Pest': 'Pest',
      'Irrigation': 'Irrigation',
      'Crop': 'Crop',
      'Notification Summary': 'Notification Summary',
      'Total': 'Total',
      'High Priority': 'High Priority',
      'No notifications': 'No notifications',
      'No unread notifications to show': 'No unread notifications to show',
      'Active': 'Active',
      'Mark as read': 'Mark as read',
      
      // Common
      'home': 'Home',
      'crops': 'Crops',
      'water': 'Water',
      'settings': 'Settings',
      'notifications': 'Notifications',
      'account': 'Account',
      'logout': 'Logout',
      'language': 'Language',
    },
    HI: {
      // Welcome & Onboarding
      'smart_kisan': 'स्मार्ट किसान',
      'empowering_farmers': 'किसानों को स्मार्ट समाधान से सशक्त बनाना',
      'get_updates': 'वास्तविक समय में मौसम अपडेट, फसल की सलाह, कीट और रोग सहायता और पानी अनुकूलन प्राप्त करें।',
      'get_started': 'शुरू करें',
      'log_in': 'लॉगिन करें',
      'choose_language': 'अपनी भाषा चुनें',
      'skip': 'छोड़ें',
      'back': 'वापस',
      'next': 'आगे',
      'English': 'English',
      'Hindi': 'हिन्दी',
      'Nepali': 'नेपाली',
      'Monitoring soil and plant': 'मिट्टी और पौधों की निगरानी',
      'We aim to use optical (VIR) sensing to observe the fields and make timely crop management decisions.': 'हम खेतों को देखने और समय पर फसल प्रबंधन निर्णय लेने के लिए ऑप्टिकल (VIR) संवेदन का उपयोग करना चाहते हैं।',
      'Crop Selection': 'फसल चयन',
      'Our project can use AI & Machine learning to select the best crop according to the land and water resources.': 'हमारी परियोजना भूमि और जल संसाधनों के अनुसार सर्वोत्तम फसल चुनने के लिए AI और मशीन लर्निंग का उपयोग कर सकती है।',
      'Improve agriculture precision': 'कृषि सटीकता में सुधार',
      'We will use satellite imagery, image processing, deep learning, computer vision, and remote sensing to detect changes in the field and crops and solve the problems whenever they pop.': 'हम खेत और फसलों में परिवर्तन का पता लगाने के लिए उपग्रह इमेजरी, छवि प्रसंस्करण, गहन शिक्षा, कंप्यूटर दृष्टि और दूर संवेदन का उपयोग करेंगे।',
      
      // Login & Registration
      'Email': 'ईमेल',
      'Password': 'पासवर्ड',
      'Sign In': 'साइन इन',
      'Don\'t have an account? Sign Up': 'खाता नहीं है? साइन अप करें',
      'Forgot Password?': 'पासवर्ड भूल गए?',
      'Remember Me': 'मुझे याद रखें',
      'Sign Up': 'साइन अप',
      'Create Account': 'खाता बनाएं',
      'Confirm Password': 'पासवर्ड की पुष्टि करें',
      'Already have an account? Sign In': 'पहले से खाता है? साइन इन करें',
      'please Log in to continue': 'जारी रखने के लिए कृपया लॉगिन करें',
      'enter_email': 'अपना ईमेल दर्ज करें',
      'enter_password': 'अपना पासवर्ड दर्ज करें',
      'Please enter your email': 'कृपया अपना ईमेल दर्ज करें',
      'Please enter your password': 'कृपया अपना पासवर्ड दर्ज करें',
      'Log in': 'लॉगिन',
      'or sign in with': 'या इसके साथ साइन इन करें',
      'Google Sign-In failed or cancelled': 'गूगल साइन-इन विफल या रद्द',
      'Forgot Password': 'पासवर्ड भूल गए',
      'Enter the email address you used when you joined and we\'ll send you instructions to reset your password.': 'वह ईमेल पता दर्ज करें जो आपने शामिल होने के समय उपयोग किया था और हम आपको पासवर्ड रीसेट करने के निर्देश भेजेंगे।',
      'Email ID': 'ईमेल आईडी',
      'Please enter email id': 'कृपया ईमेल आईडी दर्ज करें',
      'Please enter a valid email id': 'कृपया एक वैध ईमेल आईडी दर्ज करें',
      'Enter email id': 'ईमेल आईडी दर्ज करें',
      'Send Link/Code': 'लिंक/कोड भेजें',
      'Having a Problem?': 'कोई समस्या है?',
      'Send Again': 'फिर से भेजें',
      'Verify code sent': 'भेजा गया कोड सत्यापित करें',
      'Enter 4-digits code sent to you at': 'आपको भेजा गया 4-अंकीय कोड दर्ज करें',
      'Verify Code': 'कोड सत्यापित करें',
      'New Password': 'नया पासवर्ड',
      'Confirm New Password': 'नए पासवर्ड की पुष्टि करें',
      'Enter New Password': 'नया पासवर्ड दर्ज करें',
      'Please enter new password': 'कृपया नया पासवर्ड दर्ज करें',
      'Enter new password': 'नया पासवर्ड दर्ज करें',
      'Please confirm new password': 'कृपया नए पासवर्ड की पुष्टि करें',
      'Passwords do not match': 'पासवर्ड मेल नहीं खाते',
      'Confirm new password': 'नए पासवर्ड की पुष्टि करें',
      'Create New Password': 'नया पासवर्ड बनाएं',
      'Congratulations!': 'बधाई!',
      'A password reset link has been sent to your email. Please check your inbox (and spam), click the link to reset your password, and then login here.': 'एक पासवर्ड रीसेट लिंक आपके ईमेल पर भेजा गया है। कृपया अपने इनबॉक्स (और स्पैम) की जांच करें, पासवर्ड रीसेट करने के लिए लिंक पर क्लिक करें, और फिर यहां लॉगिन करें।',
      'create an account to continue': 'जारी रखने के लिए एक खाता बनाएं',
      'First Name': 'पहला नाम',
      'Please enter your first name': 'कृपया अपना पहला नाम दर्ज करें',
      'Enter your first name': 'अपना पहला नाम दर्ज करें',
      'Last Name': 'अंतिम नाम',
      'Please enter your last name': 'कृपया अपना अंतिम नाम दर्ज करें',
      'Enter your last name': 'अपना अंतिम नाम दर्ज करें',
      'Mobile Number': 'मोबाइल नंबर',
      'Please enter your mobile number': 'कृपया अपना मोबाइल नंबर दर्ज करें',
      'Enter your mobile number': 'अपना मोबाइल नंबर दर्ज करें',
      'Please enter a valid mobile number (10-15 digits)': 'कृपया एक वैध मोबाइल नंबर दर्ज करें (10-15 अंक)',
      'Please enter a valid email address': 'कृपया एक वैध ईमेल पता दर्ज करें',
      'Password must be at least 6 characters': 'पासवर्ड कम से कम 6 वर्ण होना चाहिए',
      'This email is already in use. Please log in instead.': 'यह ईमेल पहले से उपयोग में है। इसके बजाय लॉगिन करें।',
      'The email address is invalid.': 'ईमेल पता अमान्य है।',
      'The password is too weak.': 'पासवर्ड बहुत कमजोर है।',
      'An unexpected error occurred. Please try again.': 'एक अप्रत्याशित त्रुटि हुई। कृपया पुनः प्रयास करें।',
      'Already have an account?': 'पहले से खाता है?',
      'sign up': 'साइन अप',
      'or sign up with': 'या इसके साथ साइन अप करें',
      'Security Fingerprint': 'सुरक्षा फिंगरप्रिंट',
      'Scan your fingerprint to login': 'लॉगिन करने के लिए अपनी फिंगरप्रिंट स्कैन करें',
      'Use fingerprint to access': 'एक्सेस के लिए फिंगरप्रिंट का उपयोग करें',
      'Tap the icon above to scan.': 'स्कैन करने के लिए ऊपर दिए गए आइकन पर टैप करें।',
      'Tap to login with Fingerprint': 'फिंगरप्रिंट से लॉगिन करने के लिए टैप करें',
      'Use Passcode': 'पासकोड का उपयोग करें',
      'Passcode': 'पासकोड',
      'Enter PassCode': 'पासकोड दर्ज करें',
      'Submit': 'जमा करें',
      'Forgot Passcode? Login with Email': 'पासकोड भूल गए? ईमेल से लॉगिन करें',
      'Incorrect passcode. Try 1234.': 'गलत पासकोड। 1234 आजमाएं।',
      'Welcome back!': 'स्वागत है!',
      'Session expired. Login with Email first.': 'सत्र समाप्त। पहले ईमेल से लॉगिन करें।',
      'Fingerprint login is only available on Mobile Apps.': 'फिंगरप्रिंट लॉगिन केवल मोबाइल ऐप्स पर उपलब्ध है।',
      'Fingerprint not supported on this device': 'इस डिवाइस पर फिंगरप्रिंट समर्थित नहीं है',
      'Session expired. Please login with Password first.': 'सत्र समाप्त। कृपया पहले पासवर्ड से लॉगिन करें।',
      
      // Home Page
      'Good morning': 'सुप्रभात',
      'Locating...': 'स्थिति ढूंढ रहे हैं...',
      'Current Weather': 'मौजूदा मौसम',
      'Humidity': 'नमी',
      'Wind': 'हवा',
      'Visibility': 'दृश्यमानता',
      'Feels Like': 'ऐसा लगता है',
      'Farm Overview': 'खेत का अवलोकन',
      'Crop Advisory': 'फसल परामर्श',
      'Pest & Disease Help': 'कीट और रोग सहायता',
      'Water Optimization': 'पानी अनुकूलन',
      'Weather Forecast': 'मौसम पूर्वानुमान',
      'Active Crops': 'सक्रिय फसलें',
      'Tap to add crops': 'फसलें जोड़ने के लिए टैप करें',
      'Rice, Wheat, Corn': 'चावल, गेहूं, मकई',
      'Yield Rate': 'उपज दर',
      'Start farming to see': 'देखने के लिए खेती शुरू करें',
      '+5% from last season': 'पिछले मौसम से +5%',
      'Alerts': 'अलर्ट',
      'No alerts yet': 'अभी कोई अलर्ट नहीं',
      'Pest warning, Rain': 'कीट चेतावनी, बारिश',
      'Tasks Done': 'पूर्ण कार्य',
      'This week': 'इस हफ्ते',
      'Setup your farm': 'अपना खेत सेट अप करें',
      'Language / भाषा': 'भाषा / भाषा',
      'Currently: English': 'वर्तमान में: अंग्रेजी',
      'नेपाली': 'नेपाली',
      'Recent Activity': 'हाल की गतिविधि',
      'Welcome to Smart Kisan!': 'स्मार्ट किसान में स्वागत है!',
      'Just now': 'अभी',
      'Complete farm setup to get started': 'शुरू करने के लिए खेत सेटअप पूरा करें',
      '1 minute ago': '1 मिनट पहले',
      'Pest identified in tomato crop': 'टमाटर की फसल में कीट की पहचान',
      '2 hours ago': '2 घंटे पहले',
      'Weather alert: Rain expected': 'मौसम सचेतावनी: बारिश की संभावना',
      '5 hours ago': '5 घंटे पहले',
      'Home': 'होम',
      'Ask AI': 'एआई से पूछें',
      'Scan': 'स्कैन',
      'Add\nLocation': 'स्थिति\nजोड़ें',
      'EN': 'EN',
      
      // Water Optimization
      'water_optimization': 'पानी अनुकूलन',
      'land_area': 'भूमि का क्षेत्र',
      'crop_type': 'फसल का प्रकार',
      'soil_type': 'मिट्टी का प्रकार',
      'calculate': 'पानी की आवश्यकता की गणना करें',
      'weather': 'मौसम की स्थिति',
      'history': 'गणना का इतिहास',
      'no_data': 'अभी तक कोई गणना नहीं',
      'enter_area': 'कृपया भूमि क्षेत्र दर्ज करें',
      'enter_crop': 'कृपया फसल का नाम दर्ज करें',
      'water_needed': 'आवश्यक पानी',
      'daily_water': 'दैनिक पानी',
      'Total Water Required': 'कुल पानी की आवश्यकता',
      'Growing Days': 'बढ़ते दिन',
      'Recommendation': 'सिफारिश',
      'Invalid crop name. Please enter a real agricultural crop.': 'अमान्य फसल का नाम। कृपया एक वास्तविक कृषि फसल दर्ज करें।',
      'Enter area': 'क्षेत्र दर्ज करें',
      'Enter any crop (e.g., wheat, tomato, rice)': 'कोई भी फसल दर्ज करें (उदा., गेहूं, टमाटर, चावल)',
      'Water Recommendation': 'पानी की सिफारिश',
      'Weather check done': 'मौसम की जांच पूरी हुई',
      'Liters': 'लीटर',
      'L/day': 'लीटर/दिन',
      'Growing Season': 'बढ़ता मौसम',
      'days': 'दिन',
      'AI Recommendation': 'एआई सिफारिश',
      'Close': 'बंद करें',
      
      // Weather
      'Current Conditions': 'मौजूदा स्थितियां',
      'Today': 'आज',
      'Hourly Forecast': 'प्रति घंटा पूर्वानुमान',
      'Now': 'अभी',
      '+1h': '+1घ',
      '+2h': '+2घ',
      '+3h': '+3घ',
      '+4h': '+4घ',
      '+5h': '+5घ',
      '7-Day Forecast': '7 दिन का पूर्वानुमान',
      'Tomorrow': 'कल',
      'Partly Cloudy': 'आंशिक रूप से बादल',
      'Rain': 'बारिश',
      'Wednesday': 'बुधवार',
      'Cloudy': 'बादल',
      'Thursday': 'गुरुवार',
      'Friday': 'शुक्रवार',
      'Sunny': 'धूप',
      'Saturday': 'शनिवार',
      'Sunday': 'रविवार',
      'Farming Advice': 'खेती की सलाह',
      'Conditions are stable. No specific warnings.': 'स्थितियां स्थिर हैं। कोई विशिष्ट चेतावनी नहीं।',
      'Rain Detected': 'बारिश का पता चला',
      'Avoid applying fertilizers or pesticides to prevent runoff.': 'बहाव को रोकने के लिए उर्वरक या कीटनाशकों का प्रयोग न करें।',
      'Irrigation Needed': 'सिंचाई की आवश्यकता है',
      'High temperatures detected. Water crops to prevent heat stress.': 'उच्च तापमान का पता चला। गर्मी के तनाव को रोकने के लिए फसलों को पानी दें।',
      'High Winds': 'तेज हवाएं',
      'Avoid spraying pesticides as drift may occur.': 'कीटनाशकों का छिड़काव न करें क्योंकि बहाव हो सकता है।',
      'Good Field Conditions': 'अच्छी खेत की स्थितियां',
      'Ideal weather for sowing, harvesting, or equipment maintenance.': 'बुवाई, कटाई, या उपकरण रखरखाव के लिए आदर्श मौसम।',
      'Safety Warning': 'सुरक्षा चेतावनी',
      'Lightning risk. Stay away from open fields and metal equipment.': 'बिजली का जोखिम। खुले खेतों और धातु के उपकरणों से दूर रहें।',
      'Cold Stress Risk': 'ठंड का तनाव जोखिम',
      'Temperatures are low. Protect sensitive seedlings from frost.': 'तापमान कम है। संवेदनशील पौधों को ठंढ से बचाएं।',
      'Stable Conditions': 'स्थिर स्थितियां',
      'Weather is normal. Continue routine farm operations.': 'मौसम सामान्य है। नियमित खेत के कार्यों को जारी रखें।',
      'Storm Alert': 'तूफान चेतावनी',
      'Thunderstorm activity detected. Halt all field work immediately.': 'गरज के साथ बारिश की गतिविधि का पता चला। सभी क्षेत्र कार्य तुरंत रोकें।',
      'Heavy Rain Alert': 'भारी बारिश चेतावनी',
      'Heavy precipitation expected. Ensure drainage systems are clear.': 'भारी वर्षा की उम्मीद है। सुनिश्चित करें कि जल निकासी प्रणाली स्पष्ट है।',
      'Gale Warning': 'तेज हवा की चेतावनी',
      'Damaging winds detected. Secure loose structures and livestock.': 'हानिकारक हवाएं पाई गईं। ढीली संरचनाओं और पशुधन को सुरक्षित करें।',
      'Select Location': 'स्थिति चुनें',
      'Use Current GPS': 'वर्तमान GPS का उपयोग करें',
      
      // Settings
      'Settings': 'सेटिंग्स',
      'Manage your account and preferences': 'अपने खाते और प्राथमिकताओं को प्रबंधित करें',
      'Profile Settings': 'प्रोफाइल सेटिंग्स',
      'Manage your personal information': 'अपनी व्यक्तिगत जानकारी प्रबंधित करें',
      'Ramesh Kumar': 'रमेश कुमार',
      'Kumar Organic Farm': 'कुमार जैविक खेत',
      'Edit Profile': 'प्रोफाइल संपादित करें',
      'Notification Settings': 'सूचना सेटिंग्स',
      'Manage your alerts and notifications': 'अपनी सचेतावनी और सूचनाओं को प्रबंधित करें',
      'Active Notifications': 'सक्रिय सूचनाएं',
      'You have 7 notifications enabled': 'आपके पास 7 सूचनाएं सक्षम हैं',
      'You have {count} notifications enabled': 'आपके पास {count} सूचनाएं सक्षम हैं',
      '7/9': '7/9',
      'Manage Notifications': 'सूचनाओं का प्रबंधन करें',
      'Language': 'भाषा',
      'Select your preferred language': 'अपनी पसंदीदा भाषा चुनें',
      'Theme': 'थीम',
      'Choose your display theme': 'अपना प्रदर्शन थीम चुनें',
      'Light Mode': 'हल्का मोड',
      'Dark Mode': 'अंधकार मोड',
      'Auto Mode': 'स्वचालित मोड',
      'Units of Measurement': 'माप की इकाइयां',
      'Set your preferred units': 'अपनी पसंदीदा इकाइयां सेट करें',
      'Temperature': 'तापमान',
      'Celsius (°C)': 'सेल्सियस (°C)',
      'Fahrenheit (°F)': 'फारेनहाइट (°F)',
      'Area': 'क्षेत्र',
      'Acres': 'एकड़',
      'Hectares': 'हेक्टेयर',
      'Volume': 'वॉल्यूम',
      'Gallons': 'गैलन',
      'Privacy & Security': 'गोपनीयता और सुरक्षा',
      'Manage your privacy settings': 'अपनी गोपनीयता सेटिंग्स प्रबंधित करें',
      'Share Usage Data': 'उपयोग डेटा साझा करें',
      'Help improve the app': 'ऐप को बेहतर बनाने में मदद करें',
      'Analytics': 'विश्लेषण',
      'Allow analytics tracking': 'विश्लेषण ट्रैकिंग की अनुमति दें',
      'Location Tracking': 'स्थान ट्रैकिंग',
      'For weather and field data': 'मौसम और खेत के डेटा के लिए',
      'Change Password': 'पासवर्ड बदलें',
      'Two-Factor Authentication': 'दो-कारक प्रमाणीकरण',
      'About': 'के बारे में',
      'App information and version': 'ऐप जानकारी और संस्करण',
      'Smart Kisan App': 'स्मार्ट किसान ऐप',
      'Version 1.0.0': 'संस्करण 1.0.0',
      '© 2024 Smart Kisan. All rights reserved.': '© 2024 स्मार्ट किसान। सर्वाधिकार सुरक्षित।',
      'Logout': 'लॉग आउट',
      'Are you sure you want to logout?': 'क्या आप निश्चित हैं कि आप लॉग आउट करना चाहते हैं?',
      'Cancel': 'रद्द करें',
      'Change Photo': 'फोटो बदलें',
      'Full Name': 'पूरा नाम',
      'Farm Name': 'खेत का नाम',
      'Phone Number': 'फोन नंबर',
      'Location': 'स्थान',
      'Save Changes': 'परिवर्तन सहेजें',
      'Profile updated successfully!': 'प्रोफाइल सफलतापूर्वक अपडेट हुआ!',
      'Old Password': 'पुराना पासवर्ड',
      'Password Requirements:': 'पासवर्ड आवश्यकताएं:',
      'At least 6 characters': 'कम से कम 6 वर्ण',
      'Contains uppercase and lowercase letters': 'बड़े और छोटे अक्षर शामिल हैं',
      'Contains at least one number': 'कम से कम एक संख्या शामिल है',
      'Contains at least one special character': 'कम से कम एक विशेष वर्ण शामिल है',
      'Password changed successfully!': 'पासवर्ड सफलतापूर्वक बदल गया!',
      'Weather Alerts': 'मौसम अलर्ट',
      'Get notified about weather changes, rain forecasts, and temperature alerts': 'मौसम परिवर्तन, वर्षा पूर्वानुमान और तापमान सचेतावनी के बारे में सूचित होना',
      'Pest & Disease Alerts': 'कीट और रोग सचेतावनी',
      'Important pest detection notifications and disease outbreak warnings': 'महत्वपूर्ण कीट का पता लगाने की सूचनाएं और रोग प्रकोप चेतावनी',
      'Irrigation Reminders': 'सिंचाई अनुस्मारक',
      'Scheduled irrigation notifications and soil moisture alerts': 'निर्धारित सिंचाई सूचनाएं और मिट्टी की नमी सचेतावनी',
      'Crop Health Updates': 'फसल स्वास्थ्य अपडेट',
      'Monitor your crop health status and growth stage updates': 'अपनी फसल के स्वास्थ्य की स्थिति और वृद्धि चरण अपडेट की निगरानी करें',
      'Market Prices': 'बाजार की कीमतें',
      'Stay updated on crop prices and market trends': 'फसल की कीमतों और बाजार की प्रवृत्तियों पर अपडेट रहें',
      'General Updates': 'सामान्य अपडेट',
      'App updates, farming tips, and seasonal recommendations': 'ऐप अपडेट, खेती की सुझाव और मौसमी सिफारिशें',
      'Email Notifications': 'ईमेल सूचनाएं',
      'Receive alerts and updates via email': 'ईमेल के माध्यम से अलर्ट और अपडेट प्राप्त करें',
      'Push Notifications': 'पुश सूचनाएं',
      'In-app and mobile push notifications': 'ऐप-में और मोबाइल पुश सूचनाएं',
      'SMS Notifications': 'एसएमएस सूचनाएं',
      'Receive critical alerts via text message': 'पाठ संदेश के माध्यम से महत्वपूर्ण अलर्ट प्राप्त करें',
      'Enable All': 'सभी सक्षम करें',
      'Disable All': 'सभी अक्षम करें',
      'About Notifications': 'सूचनाओं के बारे में',
      'We recommend keeping critical alerts like weather and pest notifications enabled to stay informed about important farming conditions.': 'हम महत्वपूर्ण खेती की स्थितियों के बारे में सूचित रहने के लिए मौसम और कीट सूचनाओं जैसी महत्वपूर्ण सचेतावनी सक्षम रखने की सिफारिश करते हैं।',
      
      // Crop Advisory - Partial (full list would be very long, using same structure)
      'Manage fields & get recommendations': 'खेतों का प्रबंधन करें और सिफारिशें प्राप्त करें',
      'Your Fields': 'आपके खेत',
      'Add Field': 'खेत जोड़ें',
      'Crops in': 'फसलें',
      'Add Crop': 'फसल जोड़ें',
      'No fields added yet. Add one to start tracking.': 'अभी तक कोई खेत नहीं जोड़ा गया। ट्रैकिंग शुरू करने के लिए एक जोड़ें।',
      'No crops added yet': 'अभी तक कोई फसल नहीं जोड़ी गई',
      'Get Smart AI Recommendations': 'स्मार्ट एआई सिफारिशें प्राप्त करें',
      'Winter Season (Nov-Feb)': 'सर्दी का मौसम (नवंबर-फरवरी)',
      'Reduce watering frequency.': 'सिंचाई की बारंबारता कम करें।',
      'Protect sensitive crops from frost.': 'संवेदनशील फसलों को ठंढ से बचाएं।',
      'Plant cover crops for soil health.': 'मिट्टी के स्वास्थ्य के लिए कवर फसलें लगाएं।',
      'Spring Season (Mar-May)': 'वसंत ऋतु (मार्च-मई)',
      'Prepare land for planting.': 'रोपण के लिए भूमि तैयार करें।',
      'Watch for aphids.': 'एफिड्स पर नज़र रखें।',
      'Clean irrigation channels.': 'सिंचाई चैनलों को साफ करें।',
      'Monsoon Season (Jun-Sep)': 'मानसून ऋतु (जून-सितंबर)',
      'Ensure drainage to prevent waterlogging.': 'जलभराव को रोकने के लिए जल निकासी सुनिश्चित करें।',
      'Monitor for stem borer.': 'तने की बोरर के लिए निगरानी करें।',
      'Harvest rainwater.': 'वर्षा जल की कटाई करें।',
      'Autumn Season (Oct)': 'शरद ऋतु (अक्टूबर)',
      'Harvest monsoon crops.': 'मानसून की फसलों की कटाई करें।',
      'Prepare soil for wheat.': 'गेहूं के लिए मिट्टी तैयार करें।',
      'Store grains in dry places.': 'अनाज को सूखे स्थानों में संग्रहीत करें।',
      'Seasonal Tips': 'मौसमी सुझाव',
      'Add New Field': 'नया खेत जोड़ें',
      'Field Name': 'खेत का नाम',
      'e.g., South Field': 'उदा., दक्षिण खेत',
      'Size': 'आकार',
      'e.g., 2 Acres / 5 Katha': 'उदा., 2 एकड़ / 5 कठा',
      'Soil Type': 'मिट्टी का प्रकार',
      'Loamy Soil': 'दोमट मिट्टी',
      'Clay Soil': 'चिकनी मिट्टी',
      'Sandy Soil': 'रेतीली मिट्टी',
      'Silt Soil': 'गाद मिट्टी',
      'Peaty Soil': 'पीट मिट्टी',
      'Chalky Soil': 'चाकी मिट्टी',
      'Black Soil': 'काली मिट्टी',
      'Save': 'सहेजें',
      'Wait 2 seconds before adding another field': 'दूसरा खेत जोड़ने से पहले 2 सेकंड प्रतीक्षा करें',
      'Max 10 fields allowed per account': 'प्रति खाते 10 खेतों की अनुमति है',
      'Error:': 'त्रुटि:',
      'Custom Crop Name': 'कस्टम फसल का नाम',
      'Enter Name': 'नाम दर्ज करें',
      'Add Custom Crop': 'कस्टम फसल जोड़ें',
      'Or Select Common Crop:': 'या सामान्य फसल चुनें:',
      'Rice (Paddy)': 'चावल (पद्दी)',
      'Monsoon': 'मानसून',
      '100-150 days': '100-150 दिन',
      'High': 'ऊँचा',
      'Wheat': 'गेहूं',
      'Winter': 'सर्दी',
      '110-130 days': '110-130 दिन',
      'Medium': 'माध्यम',
      'Maize (Corn)': 'मकई (कॉर्न)',
      'Spring/Summer': 'वसंत/गर्मी',
      '90-110 days': '90-110 दिन',
      'Millet (Kodo)': 'ज्वार (कोडो)',
      'Summer': 'गर्मी',
      '100-120 days': '100-120 दिन',
      'Low': 'कम',
      'Barley (Jau)': 'जौ (जौ)',
      'Buckwheat (Phapar)': 'कुट्टू (फापर)',
      'Autumn': 'शरद',
      '70-90 days': '70-90 दिन',
      'Potato': 'आलू',
      '90-120 days': '90-120 दिन',
      'Tomato': 'टमाटर',
      'All Year': 'पूरे साल',
      '90-100 days': '90-100 दिन',
      'Cauliflower': 'फूलगोभी',
      '80-100 days': '80-100 दिन',
      'Cabbage': 'पत्तागोभी',
      'Onion': 'प्याज',
      '120-150 days': '120-150 दिन',
      'Garlic': 'लहसुन',
      '130-160 days': '130-160 दिन',
      'Ginger': 'अदरक',
      '240-270 days': '240-270 दिन',
      'Radish': 'मूली',
      '40-60 days': '40-60 दिन',
      'Carrot': 'गाजर',
      'Brinjal (Eggplant)': 'बैंगन',
      'Okra (Lady Finger)': 'भिंडी',
      '60-90 days': '60-90 दिन',
      'Spinach (Saag)': 'पालक',
      '30-45 days': '30-45 दिन',
      'Cucumber': 'खीरा',
      '60-80 days': '60-80 दिन',
      'Pumpkin': 'कद्दू',
      'Bitter Gourd (Karela)': 'करेला',
      'Bottle Gourd (Lauka)': 'लौकी',
      'Chili': 'मिर्च',
      'Peas': 'मटर',
      'Broad Bean (Bakulla)': 'व्यापक बीन',
      'Lentil (Musuro)': 'दाल',
      'Chickpea (Chana)': 'चना',
      'Black Gram (Mas)': 'काली दाल',
      'Soybean': 'सोयाबीन',
      'Pigeon Pea (Rahar)': 'अरहर',
      'Mung Bean': 'मूंग',
      'Mustard': 'सरसों',
      'Sugarcane': 'गन्ना',
      'Spring': 'वसंत',
      '300-365 days': '300-365 दिन',
      'Tea': 'चाय',
      'Perennial': 'बहुवर्षीय',
      'Years': 'साल',
      'Coffee': 'कॉफी',
      'Cardamom (Alaichi)': 'इलायची',
      'Jute': 'जूट',
      'Sunflower': 'सूरजमुखी',
      'Groundnut (Peanut)': 'मूंगफली',
      'Turmeric': 'हल्दी',
      'Banana': 'केला',
      '12-14 months': '12-14 महीने',
      'Mango': 'आम',
      'Apple': 'सेब',
      'Orange/Citrus': 'संतरा/खट्टे फल',
      'Papaya': 'पपीता',
      '9-12 months': '9-12 महीने',
      'Guava': 'अमरूद',
      'Lychee': 'लीची',
      'Watermelon': 'तरबूज',
      'Max 20 crops per field allowed': 'प्रति खेत 20 फसलों की अनुमति है',
      'Delete Field?': 'खेत हटाएं?',
      'This will delete the field and all crops inside it.': 'यह खेत और इसके अंदर की सभी फसलों को हटा देगा।',
      'Delete': 'हटाएं',
      'AI Recommendations': 'एआई सिफारिशें',
      'Suggested Crops (tap + to add):': 'सुझाई गई फसलें (जोड़ने के लिए + पर टैप करें):',
      'Added': 'जोड़ा गया',
      'to field': 'खेत में',
      'Edit': 'संपादित करें',
      
      // Pest & Disease Help
      'Early detection and treatment guidance': 'प्रारंभिक पहचान और उपचार मार्गदर्शन',
      'Scan Your Crop': 'अपनी फसल स्कैन करें',
      'Use your camera to identify pests and diseases': 'कीटों और रोगों की पहचान करने के लिए अपने कैमरे का उपयोग करें',
      'Scan Now': 'अभी स्कैन करें',
      'Active Alerts': 'सक्रिय सचेतावनी',
      'No active alerts. Your crops are looking healthy!': 'कोई सक्रिय सचेतावनी नहीं। आपकी फसलें स्वस्थ दिख रही हैं!',
      'Treatment:': 'उपचार:',
      'Detected:': 'पाया गया:',
      'Recent Scans': 'हाल के स्कैन',
      'No scans yet. Start by scanning a crop!': 'अभी तक कोई स्कैन नहीं। एक फसल स्कैन करके शुरू करें!',
      'Prevention Tips': 'रोकथाम सुझाव',
      'Regular field inspections to catch issues early': 'समस्याओं को जल्दी पकड़ने के लिए नियमित खेत का निरीक्षण',
      'Crop rotation to prevent pest buildup': 'कीटों के निर्माण को रोकने के लिए फसल रोटेशन',
      'Maintain proper plant spacing for air circulation': 'वायु संचार के लिए उचित पौधों की दूरी बनाए रखें',
      'Remove plant debris to reduce disease habitat': 'रोग के आवास को कम करने के लिए पौधों के मलबे को हटाएं',
      'Use disease-resistant crop varieties when available': 'जब उपलब्ध हो तो रोग-प्रतिरोधी फसल की किस्मों का उपयोग करें',
      'Search Knowledge Base': 'ज्ञान आधार खोजें',
      'Find information about pests and diseases': 'कीटों और रोगों के बारे में जानकारी खोजें',
      'Search': 'खोज',
      'This feature will open your camera to scan crops for pests and diseases.': 'यह सुविधा कीटों और रोगों के लिए फसलों को स्कैन करने के लिए आपका कैमरा खोलेगी।',
      'Make sure to:': 'सुनिश्चित करें:',
      '1. Focus on the affected area': '1. प्रभावित क्षेत्र पर ध्यान केंद्रित करें',
      '2. Use good lighting': '2. अच्छी रोशनी का उपयोग करें',
      '3. Keep camera steady': '3. कैमरे को स्थिर रखें',
      'Open Camera': 'कैमरा खोलें',
      'Analyzing crop image...': 'फसल की छवि का विश्लेषण जारी है...',
      'Scan Results': 'स्कैन परिणाम',
      'Crop:': 'फसल:',
      'Unknown': 'अज्ञात',
      'Status:': 'स्थिति:',
      'Confidence:': 'आत्मविश्वास:',
      '%': '%',
      'Save Result': 'परिणाम सहेजें',
      'Scan saved to history': 'स्कैन इतिहास में सहेजा गया',
      'Mark Resolved': 'समाधान को चिह्नित करें',
      'Alert marked as resolved': 'सचेतावनी को समाधान के रूप में चिह्नित किया गया',
      'Enter keywords like "aphids", "leaf blight", "corn diseases", etc.': 'कीवर्ड दर्ज करें जैसे "एफिड्स", "पत्ती झुलसा", "मकई रोग", आदि।',
      'Search for': 'खोज करें',
      'Fetching information...': 'जानकारी प्राप्त जारी है...',
      'Information about': 'के बारे में जानकारी',
      'No information found. Please try another search.': 'कोई जानकारी नहीं मिली। कृपया दूसरी खोज आजमाएं।',
      
      // Scan Page
      'AI-powered disease & pest detection': 'एआई-संचालित रोग और कीट पहचान',
      'Total Scans': 'कुल स्कैन',
      'Healthy': 'स्वस्थ',
      'Issues Found': 'समस्याएं मिलीं',
      'Start New Scan': 'नया स्कैन शुरू करें',
      'Take Photo': 'फोटो लें',
      'Use camera': 'कैमरा का उपयोग करें',
      'Upload Image': 'छवि अपलोड करें',
      'From gallery': 'गैलरी से',
      'How to get best results': 'सर्वोत्तम परिणाम कैसे प्राप्त करें',
      '• Take clear, well-lit photos': '• स्पष्ट, अच्छी तरह से रोशन वाली तस्वीरें लें',
      '• Focus on affected areas': '• प्रभावित क्षेत्रों पर ध्यान दें',
      '• Include whole leaf when possible': '• जब संभव हो तो पूरी पत्ती शामिल करें',
      '• Avoid blurry or dark images': '• धुंधली या अंधकार छवियों से बचें',
      'No scans yet': 'अभी तक कोई स्कैन नहीं',
      'Start by taking a photo or uploading an image': 'एक फोटो लेकर या एक छवि अपलोड करके शुरू करें',
      'Camera Access': 'कैमरा एक्सेस',
      'This feature will open the camera for scanning in the next phase.': 'यह सुविधा अगले चरण में स्कैनिंग के लिए कैमरा खोलेगी।',
      'You can take photos of crops for disease detection.': 'आप रोग पहचान के लिए फसलों की तस्वीरें ले सकते हैं।',
      'This feature will open the gallery for image selection in the next phase.': 'यह सुविधा अगले चरण में छवि चयन के लिए गैलरी खोलेगी।',
      'You can upload crop photos for analysis.': 'आप विश्लेषण के लिए फसल की तस्वीरें अपलोड कर सकते हैं।',
      'Choose Image': 'छवि चुनें',
      'Scan Details': 'स्कैन विवरण',
      'View Details →': 'विवरण देखें →',
      
      // Location Page
      'My Locations': 'मेरे स्थान',
      'Manage your farm fields': 'अपने खेतों का प्रबंधन करें',
      'Current Location': 'मौजूदा स्थान',
      'Kathmandu, Nepal': 'काठमांडू, नेपाल',
      'Update': 'अपडेट',
      'Map View': 'नक्शा दृश्य',
      'Showing all your fields': 'आपके सभी खेत दिखा रहे हैं',
      'Saved Fields': 'सहेजे गए खेत',
      'Main Rice Field': 'मुख्य चावल का खेत',
      'Primary': 'प्राथमिक',
      '2.5 acres': '2.5 एकड़',
      '27.7172° N, 85.3240° E': '27.7172° N, 85.3240° E',
      'North Wheat Field': 'उत्तरी गेहूं खेत',
      '1.8 acres': '1.8 एकड़',
      '27.7185° N, 85.3255° E': '27.7185° N, 85.3255° E',
      'South Corn Field': 'दक्षिण मकई खेत',
      '3.2 acres': '3.2 एकड़',
      'Corn, Vegetables': 'मकई, सब्जियां',
      '27.7160° N, 85.3230° E': '27.7160° N, 85.3230° E',
      'Overview': 'सारांश',
      'Total Fields': 'कुल खेत',
      'Total Area': 'कुल क्षेत्र',
      'acres': 'एकड़',
      'Crop Types': 'फसल के प्रकार',
      'Location-Based Insights': 'स्थान-आधारित अंतर्दृष्टि',
      'Get weather forecasts, soil recommendations, and alerts specific to each field location.': 'प्रत्येक खेत की स्थिति के लिए मौसम पूर्वानुमान, मिट्टी की सिफारिशें और सचेतावनी प्राप्त करें।',
      'This feature will access your current location or allow you to search for a new location in the next phase.': 'यह सुविधा आपके वर्तमान स्थान तक पहुंचेगी या अगले चरण में एक नई स्थान खोजने की अनुमति देगी।',
      'This feature will allow you to add a new farm field with location, size, and crop information in the next phase.': 'यह सुविधा अगले चरण में स्थान, आकार और फसल जानकारी के साथ एक नया खेत जोड़ने की अनुमति देगी।',
      'Editing': 'संपादन',
      'Delete Field': 'खेत हटाएं',
      'Are you sure you want to delete': 'क्या आप निश्चित हैं कि आप हटाना चाहते हैं',
      'Navigate to Field': 'खेत पर नेविगेट करें',
      'Opening navigation to': 'नेविगेशन खोल रहे हैं',
      'at coordinates': 'निर्देशांक पर',
      'This will open your preferred map app in the next phase.': 'यह अगले चरण में आपकी पसंदीदा नक्शा ऐप खोलेगा।',
      'Field Details': 'खेत विवरण',
      'Name:': 'नाम:',
      'Area:': 'क्षेत्र:',
      'Active Crops:': 'सक्रिय फसलें:',
      'Coordinates:': 'निर्देशांक:',
      'Navigate': 'नेविगेट',
      'View Details': 'विवरण देखें',
      
      // AI Chat
      'Smart Kisan AI': 'स्मार्ट किसान एआई',
      'Your Expert Assistant': 'आपका विशेषज्ञ सहायक',
      'Quick Questions:': 'त्वरित सवाल:',
      'Best fertilizer for rice?': 'चावल के लिए सर्वोत्तम खाद?',
      'Identify this pest': 'इस कीट की पहचान करें',
      'Irrigation for wheat?': 'गेहूं के लिए सिंचाई?',
      'Tomorrow\'s weather?': 'कल का मौसम?',
      'Start chatting with Smart Kisan': 'स्मार्ट किसान के साथ बातचीत शुरू करें',
      'Ask about farming...': 'खेती के बारे में पूछें...',
      
      // Notifications
      'Notifications': 'सूचनाएं',
      'unread notifications': 'अपठित सूचनाएं',
      'Filter': 'फ़िल्टर',
      'Mark all read': 'सभी को पढ़ा हुआ चिह्नित करें',
      'Clear all': 'सभी साफ करें',
      'Filter Notifications': 'सूचनाओं को फ़िल्टर करें',
      'All': 'सभी',
      'Unread': 'अपठित',
      'Weather': 'मौसम',
      'Pest': 'कीट',
      'Irrigation': 'सिंचाई',
      'Crop': 'फसल',
      'Add Location': 'स्थान जोड़ें',
      'Loading...': 'लोड हो रहा है...',
      'Notification Summary': 'सूचना सारांश',
      'Total': 'कुल',
      'High Priority': 'उच्च प्राथमिकता',
      'No notifications': 'कोई सूचना नहीं',
      'No unread notifications to show': 'दिखाने के लिए कोई अपठित सूचना नहीं',
      'Active': 'सक्रिय',
      'Mark as read': 'पढ़ा हुआ चिह्नित करें',
      
      // Common
      'home': 'होम',
      'crops': 'फसलें',
      'water': 'पानी',
      'settings': 'सेटिंग्स',
      'notifications': 'सूचनाएं',
      'account': 'खाता',
      'logout': 'लॉग आउट',
      'language': 'भाषा',
    },
    NE: {
      // Welcome & Onboarding
      'smart_kisan': 'स्मार्ट किसान',
      'empowering_farmers': 'स्मार्ट समाधानको साथ किसानहरूलाई शक्तिशाली बनाउँदै',
      'get_updates': 'रियल-टाइम मौसम अपडेट, फसलको सल्लाह, कीटपतङ्ग र रोग सहायता र पानी अनुकूलन प्राप्त गर्नुहोस्।',
      'get_started': 'शुरू गर्नुहोस्',
        'You have {count} notifications enabled': 'तपाईंको {count} सूचनाहरू सक्षम छन्',
      'log_in': 'लगइन गर्नुहोस्',
      'choose_language': 'आपनो भाषा छान्नुहोस्',
      'skip': 'छोड्नुहोस्',
      'back': 'पछाडी',
      'next': 'अगाडी',
      'English': 'English',
      'Hindi': 'हिन्दी',
      'Nepali': 'नेपाली',
      'Monitoring soil and plant': 'माटो र बिरुवाको निरीक्षण गर्नुहोस्',
      'We aim to use optical (VIR) sensing to observe the fields and make timely crop management decisions.': 'हामी खेतहरूलाई अवलोकन गर्न र समयमा फसलको व्यवस्थापन निर्णय लिन अप्टिकल (VIR) सेन्सिङको प्रयोग गर्न चाहन्छौं।',
      'Crop Selection': 'फसल चयन',
      'Our project can use AI & Machine learning to select the best crop according to the land and water resources.': 'हाम्रो परियोजनाले जमीन र पानीको संसाधनहरू अनुसार सर्वश्रेष्ठ फसल छन्न AI र मेसिन लर्निङ प्रयोग गर्न सक्छ।',
      'Improve agriculture precision': 'कृषि सटीकता सुधार गर्नुहोस्',
      'We will use satellite imagery, image processing, deep learning, computer vision, and remote sensing to detect changes in the field and crops and solve the problems whenever they pop.': 'हामी खेत र फसलहरूमा परिवर्तन पत्ता लगाउन उपग्रह इमेजरी, छवि प्रसंस्करण, गहिरो सिकाई, कम्प्युटर दृष्टि र रिमोट सेन्सिङ प्रयोग गर्नेछौं।',
      
      // Login & Registration  
      'Email': 'ईमेल',
      'Password': 'पासवर्ड',
      'Sign In': 'साइन इन',
      'Don\'t have an account? Sign Up': 'खाता नछ? साइन अप गर्नुहोस्',
      'Forgot Password?': 'पासवर्ड बिर्सनुभयो?',
      'Remember Me': 'मलाई याद राख',
      'Sign Up': 'साइन अप',
      'Create Account': 'खाता बनाउनुहोस्',
      'Confirm Password': 'पासवर्ड पुष्टि गर्नुहोस्',
      'Already have an account? Sign In': 'पहिले नै खाता छ? साइन इन गर्नुहोस्',
      'please Log in to continue': 'जारी राख्नको लागि कृपया लगइन गर्नुहोस्',
      'enter_email': 'आपनो ईमेल प्रविष्ट गर्नुहोस्',
      'enter_password': 'आपनो पासवर्ड प्रविष्ट गर्नुहोस्',
      'Please enter your email': 'कृपया आपनो ईमेल प्रविष्ट गर्नुहोस्',
      'Please enter your password': 'कृपया आपनो पासवर्ड प्रविष्ट गर्नुहोस्',
      'Log in': 'लगइन',
      'or sign in with': 'वा यसको साथ लगइन गर्नुहोस्',
      'Google Sign-In failed or cancelled': 'गुगल साइन-इन विफल भयो वा रद्द',
      'Forgot Password': 'पासवर्ड बिर्सनुभयो',
      'Enter the email address you used when you joined and we\'ll send you instructions to reset your password.': 'आपनो ईमेल पता दर्ज गर्नुहोस् जुन तपाईंले जोडिदा प्रयोग गर्नुभयो र हामी आपनो पासवर्ड रिसेट गर्नको लागि निर्देशन पठाउनेछौं।',
      'Email ID': 'ईमेल आईडी',
      'Please enter email id': 'कृपया ईमेल आईडी प्रविष्ट गर्नुहोस्',
      'Please enter a valid email id': 'कृपया वैध ईमेल आईडी प्रविष्ट गर्नुहोस्',
      'Enter email id': 'ईमेल आईडी प्रविष्ट गर्नुहोस्',
      'Send Link/Code': 'लिङ्क/कोड पठाउनुहोस्',
      'Having a Problem?': 'कोई समस्या छ?',
      'Send Again': 'फिर पठाउनुहोस्',
      'Verify code sent': 'पठाइएको कोड पुष्टि गर्नुहोस्',
      'Enter 4-digits code sent to you at': 'तपाईंलाई पठाइएको 4-अङ्कको कोड प्रविष्ट गर्नुहोस्',
      'Verify Code': 'कोड पुष्टि गर्नुहोस्',
      'New Password': 'नयाँ पासवर्ड',
      'Confirm New Password': 'नयाँ पासवर्ड पुष्टि गर्नुहोस्',
      'Enter New Password': 'नयाँ पासवर्ड प्रविष्ट गर्नुहोस्',
      'Please enter new password': 'कृपया नयाँ पासवर्ड प्रविष्ट गर्नुहोस्',
      'Enter new password': 'नयाँ पासवर्ड प्रविष्ट गर्नुहोस्',
      'Please confirm new password': 'कृपया नयाँ पासवर्ड पुष्टि गर्नुहोस्',
      'Passwords do not match': 'पासवर्ड मेल खाइरहेको छैन',
      'Confirm new password': 'नयाँ पासवर्ड पुष्टि गर्नुहोस्',
      'Create New Password': 'नयाँ पासवर्ड सिर्जना गर्नुहोस्',
      'Congratulations!': 'बधाई छ!',
      'A password reset link has been sent to your email. Please check your inbox (and spam), click the link to reset your password, and then login here.': 'पासवर्ड रिसेट गर्ने लिङ्क आपनो ईमेलमा पठाइएको छ। कृपया आपनो इनबॉक्स (र स्प्याम) जांच गर्नुहोस्, पासवर्ड रिसेट गर्नको लागि लिङ्कमा क्लिक गर्नुहोस्, र त्यसपछि यहाँ लगइन गर्नुहोस्।',
      'create an account to continue': 'जारी राख्नको लागि खाता सिर्जना गर्नुहोस्',
      'First Name': 'पहिलो नाम',
      'Please enter your first name': 'कृपया आपनो पहिलो नाम प्रविष्ट गर्नुहोस्',
      'Enter your first name': 'आपनो पहिलो नाम प्रविष्ट गर्नुहोस्',
      'Last Name': 'अन्तिम नाम',
      'Please enter your last name': 'कृपया आपनो अन्तिम नाम प्रविष्ट गर्नुहोस्',
      'Enter your last name': 'आपनो अन्तिम नाम प्रविष्ट गर्नुहोस्',
      'Mobile Number': 'मोबाइल नम्बर',
      'Please enter your mobile number': 'कृपया आपनो मोबाइल नम्बर प्रविष्ट गर्नुहोस्',
      'Enter your mobile number': 'आपनो मोबाइल नम्बर प्रविष्ट गर्नुहोस्',
      'Please enter a valid mobile number (10-15 digits)': 'कृपया वैध मोबाइल नम्बर प्रविष्ट गर्नुहोस् (10-15 अङ्क)',
      'Please enter a valid email address': 'कृपया वैध ईमेल पता प्रविष्ट गर्नुहोस्',
      'Password must be at least 6 characters': 'पासवर्ड कम से कम 6 वर्ण हुनु पर्छ',
      'This email is already in use. Please log in instead.': 'यो ईमेल पहिले नै प्रयोगमा छ। यसको सट्टा लगइन गर्नुहोस्।',
      'The email address is invalid.': 'ईमेल पता अमान्य छ।',
      'The password is too weak.': 'पासवर्ड बहुत कमजोर छ।',
      'An unexpected error occurred. Please try again.': 'अप्रत्याशित त्रुटि भयो। कृपया फिर प्रयास गर्नुहोस्।',
      'Already have an account?': 'पहिले नै खाता छ?',
      'sign up': 'साइन अप',
      'or sign up with': 'वा यसको साथ साइन अप गर्नुहोस्',
      'Security Fingerprint': 'सुरक्षा फिङ्गरप्रिन्ट',
      'Scan your fingerprint to login': 'लगइन गर्नको लागि आपनो फिङ्गरप्रिन्ट स्क्यान गर्नुहोस्',
      'Use fingerprint to access': 'पहुँचको लागि फिङ्गरप्रिन्ट प्रयोग गर्नुहोस्',
      'Tap the icon above to scan.': 'स्क्यान गर्नको लागि माथिको आइकनमा ट्याप गर्नुहोस्।',
      'Tap to login with Fingerprint': 'फिङ्गरप्रिन्टसँग लगइन गर्नको लागि ट्याप गर्नुहोस्',
      'Use Passcode': 'पासकोड प्रयोग गर्नुहोस्',
      'Passcode': 'पासकोड',
      'Enter PassCode': 'पासकोड प्रविष्ट गर्नुहोस्',
      'Submit': 'जमा गर्नुहोस्',
      'Forgot Passcode? Login with Email': 'पासकोड बिर्सनुभयो? ईमेलको साथ लगइन गर्नुहोस्',
      'Incorrect passcode. Try 1234.': 'गलत पासकोड। 1234 प्रयास गर्नुहोस्।',
      'Welcome back!': 'स्वागत छ!',
      'Session expired. Login with Email first.': 'सत्र समाप्त भयो। पहिले ईमेलको साथ लगइन गर्नुहोस्।',
      'Fingerprint login is only available on Mobile Apps.': 'फिङ्गरप्रिन्ट लगइन केवल मोबाइल एप्समा उपलब्ध छ।',
      'Fingerprint not supported on this device': 'यस उपकरणमा फिङ्गरप्रिन्ट समर्थित छैन',
      'Session expired. Please login with Password first.': 'सत्र समाप्त भयो। कृपया पहिले पासवर्डको साथ लगइन गर्नुहोस्।',
      
      // Home Page
      'Good morning': 'शुभप्रभात',
      'Locating...': 'स्थान खोज्दै...',
      'Current Weather': 'वर्तमान मौसम',
      'Humidity': 'आर्द्रता',
      'Wind': 'हवा',
      'Visibility': 'दृश्यमानता',
      'Feels Like': 'यो लाग्छ',
      'Farm Overview': 'खेत को अवलोकन',
      'Crop Advisory': 'फसल सल्लाह',
      'Pest & Disease Help': 'कीट र रोग सहायता',
      'Water Optimization': 'पानी अनुकूलन',
      'Weather Forecast': 'मौसम पूर्वानुमान',
      'Active Crops': 'सक्रिय फसलें',
      'Tap to add crops': 'फसलें थप्नको लागि ट्याप गर्नुहोस्',
      'Rice, Wheat, Corn': 'धान, गेहूँ, मकै',
      'Yield Rate': 'उपज दर',
      'Start farming to see': 'देख्नको लागि खेती सुरु गर्नुहोस्',
      '+5% from last season': 'गत मौसमबाट +5%',
      'Alerts': 'सचेतावनी',
      'No alerts yet': 'अभी कोई सचेतावनी छैन',
      'Pest warning, Rain': 'कीट चेतावनी, वर्षा',
      'Tasks Done': 'पूर्ण कार्य',
      'This week': 'यो साताह',
      'Setup your farm': 'आपनो खेत सेटअप गर्नुहोस्',
      'Language / भाषा': 'भाषा / भाषा',
      'Currently: English': 'वर्तमान: अङ्ग्रेजी',
      'नेपाली': 'नेपाली',
      'Recent Activity': 'हालको गतिविधि',
      'Welcome to Smart Kisan!': 'स्मार्ट किसानमा स्वागत छ!',
      'Just now': 'भर्खर',
      'Complete farm setup to get started': 'सुरु गर्नको लागि खेत सेटअप पूरा गर्नुहोस्',
      '1 minute ago': '1 मिनेट अगाडी',
      'Pest identified in tomato crop': 'टमाटरको फसलमा कीट पहिचान',
      '2 hours ago': '2 घण्टा अगाडी',
      'Weather alert: Rain expected': 'मौसम सचेतावनी: वर्षा को अपेक्षा',
      '5 hours ago': '5 घण्टा अगाडी',
      'Home': 'घर',
      'Ask AI': 'एआईलाई सोध्नुहोस्',
      'Scan': 'स्क्यान',
      'Add\nLocation': 'स्थान\n थप्नुहोस्',
      'EN': 'EN',
      
      // Water Optimization (continuing with Nepali - abbreviated for brevity, full translations would follow same pattern)
      'water_optimization': 'पानी अनुकूलन',
      'land_area': 'भूमि क्षेत्र',
      'crop_type': 'फसल को प्रकार',
      'soil_type': 'माटो को प्रकार',
      'calculate': 'पानी को आवश्यकता गणना गर्नुहोस्',
      'weather': 'मौसम स्थिति',
      'history': 'गणना इतिहास',
      'no_data': 'अभी कोई गणना छैन',
      'enter_area': 'कृपया भूमि क्षेत्र प्रविष्ट गर्नुहोस्',
      'enter_crop': 'कृपया फसल को नाम प्रविष्ट गर्नुहोस्',
      'water_needed': 'आवश्यक पानी',
      'daily_water': 'दैनिक पानी',
      'Total Water Required': 'कुल पानी को आवश्यकता',
      'Growing Days': 'बढ्दै गर्छ दिनहरु',
      'Recommendation': 'सिफारिश',
      'Invalid crop name. Please enter a real agricultural crop.': 'अमान्य फसल को नाम। कृपया वास्तविक कृषि फसल प्रविष्ट गर्नुहोस्।',
      'Enter area': 'क्षेत्र प्रविष्ट गर्नुहोस्',
      'Enter any crop (e.g., wheat, tomato, rice)': 'कोई फसल प्रविष्ट गर्नुहोस् (उदा., गेहूँ, टमाटर, धान)',
      'Water Recommendation': 'पानी को सिफारिश',
      'Weather check done': 'मौसम को जांच पूरी भयो',
      'Liters': 'लिटर',
      'L/day': 'लिटर/दिन',
      'Growing Season': 'बढ्दै मौसम',
      'days': 'दिनहरु',
      'AI Recommendation': 'एआई सिफारिश',
      'Close': 'बन्द गर्नुहोस्',
      
      // Common (abbreviated for brevity, full translations would follow same pattern)
      'home': 'घर',
      'crops': 'फसलें',
      'water': 'पानी',
      'settings': 'सेटिङहरू',
      'notifications': 'सूचनाहरू',
      'account': 'खाता',
      'logout': 'लगआउट',
      'language': 'भाषा',
      
      // Additional entries for other pages (abbreviated)
      'Settings': 'सेटिङहरू',
      'Profile Settings': 'प्रोफाइल सेटिङहरू',
      'Edit Profile': 'प्रोफाइल संपादन गर्नुहोस्',
      'Manage your account and preferences': 'आपनो खाता र प्राथमिकताहरु प्रबन्ध गर्नुहोस्',
      'Manage your personal information': 'आपनो व्यक्तिगत जानकारी प्रबन्ध गर्नुहोस्',
      'Current Conditions': 'वर्तमान स्थितिहरु',
      'Today': 'आज',
      'Tomorrow': 'भोलि',
      'Sunny': 'घाम',
      'Cloudy': 'बादल',
      'Partly Cloudy': 'आंशिक रूप से बादल',
      'Rain': 'वर्षा',
      'Add Field': 'खेत थप्नुहोस्',
      'Add Crop': 'फसल थप्नुहोस्',
      'Manage fields & get recommendations': 'खेतहरु प्रबन्ध गर्नुहोस् र सिफारिशहरु पाउनुहोस्',
      'Scan Your Crop': 'आपनो फसल स्क्यान गर्नुहोस्',
      'Scan Now': 'अभी स्क्यान गर्नुहोस्',
      'Notifications': 'सूचनाहरू',
      'Mark all read': 'सबै पढिएको चिन्ह लगाउनुहोस्',
      'Filter': 'फिल्टर गर्नुहोस्',
    }
  };

  static String translate(String key, {String? language}) {
    final lang = language ?? _currentLanguage;
    return _translations[lang]?[key] ?? key;
  }

  static Locale getLocale(String languageCode) {
    switch (languageCode) {
      case HI:
        return const Locale('hi', 'IN');
      case NE:
        return const Locale('ne', 'NP');
      default:
        return const Locale('en', 'US');
    }
  }
}

// LocalizationProvider - A notifier that manages language changes
class LocalizationProvider extends ChangeNotifier {
  String _currentLanguage = LocalizationService.EN;

  String get currentLanguage => _currentLanguage;

  void setLanguage(String languageCode) {
    if (_currentLanguage != languageCode) {
      _currentLanguage = languageCode;
      LocalizationService.setLanguage(languageCode);
      notifyListeners();
    }
  }

  String translate(String key) {
    return LocalizationService.translate(key, language: _currentLanguage);
  }
}
