import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'dart:async';
import 'firebase_options.dart';       
import 'welcome_screen.dart';
import 'home_page.dart';
import 'user_registration.dart';
import 'localization_service.dart';
import 'notification_service.dart';

import 'package:easy_localization/easy_localization.dart';

/// Purpose: The entry point of the Smart Kisan application. Initializes Firebase, local notifications, and global localization.
/// Inputs: Standard Flutter environment inputs.
/// Outputs: Bootstraps and runs the [MyApp] root widget.
Future<void> main() async {
  // 1. Ensure the Flutter engine is fully bound to the native platform before calling any async plugin code.
  WidgetsFlutterBinding.ensureInitialized();

  try {
    // 2. Initialize the Firebase SDK, using platform-specific settings generated by flutterfire.
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    // 3. Instantiate the global NotificationService to handle push alerts.
    final notificationService = NotificationService();
    // 4. Request device permissions and configure local notification channels.
    await notificationService.initFCM();
  } catch (e) {
    // 5. Catch initialization errors gracefully so the app can still boot (e.g. offline mode).
    print(' Firebase initialization warning: $e');
  }

  // 6. Retrieve the user's previously saved language preference from SharedPreferences.
  await LocalizationService.loadLanguage();
  // 7. Initialize the easy_localization engine to prepare translation assets.
  await EasyLocalization.ensureInitialized();

  // 8. Inflate the root widget, wrapping it in the localization provider.
  runApp(
    EasyLocalization(
      supportedLocales: const [Locale('en'), Locale('hi'), Locale('ne')],
      path: 'assets/translations',
      fallbackLocale: const Locale('en'),
      child: const MyApp(),
    ),
  );
}

/// Purpose: The root stateful widget of the application. Manages global Theme and Notification stream subscriptions.
class MyApp extends StatefulWidget {
  const MyApp({super.key});

  static _MyAppState? of(BuildContext context) => context.findAncestorStateOfType<_MyAppState>();
  static GlobalKey<NavigatorState> get navigatorKey => _MyAppState.navigatorKey;

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  late LocalizationProvider _localizationProvider;
  ThemeMode _themeMode = ThemeMode.system;
  static final GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();
  StreamSubscription<User?>? _authSub;
  StreamSubscription? _notifSub;

  @override
  void initState() {
    super.initState();
    _localizationProvider = LocalizationProvider();
    _localizationProvider.addListener(() {
      setState(() {});
    });
    _loadThemePreference();
    _initializeNotifications();
  }

  /// Purpose: Asynchronously loads the user's last selected UI theme from disk.
  /// Inputs: None.
  /// Outputs: Updates [_themeMode] and triggers a rebuild.
  Future<void> _loadThemePreference() async {
    try {
      // 1. Open the local SharedPreferences instance.
      final prefs = await SharedPreferences.getInstance();
      // 2. Fetch the stored string, defaulting to 'Auto Mode' if none exists.
      final theme = prefs.getString('ui_theme') ?? 'Auto Mode';
      print(' Loading theme from preferences: $theme');
      
      // 3. Convert the string to a native Flutter ThemeMode enum and update state.
      setState(() {
        _themeMode = _stringToThemeMode(theme);
      });
      print(' Theme loaded: $_themeMode');
    } catch (e) {
      // 4. Log any file system errors without crashing.
      print(' Error loading theme: $e');
    }
  }

  /// Purpose: Sets up the authentication listener. If a user is logged in, it attaches to their specific Firestore notification stream.
  /// Inputs: None.
  /// Outputs: Modifies the [_authSub] subscription.
  void _initializeNotifications() {
    try {
      // 1. Grab the singleton FirebaseAuth instance.
      final auth = FirebaseAuth.instance;

      // 2. Immediate check: If the app cold-boots and the user is already logged in, attach the stream immediately.
      if (auth.currentUser != null) {
        _attachNotificationListener();
      }

      // 3. Reactive check: Listen for future sign-ins or sign-outs during the app's lifecycle.
      _authSub = auth.authStateChanges().listen((user) {
        if (user != null) {
          // 4. User logged in: safe to query their private Firestore collections.
          _attachNotificationListener();
        } else {
          // 5. User signed out: cancel the active snapshot listener to prevent permission errors and memory leaks.
          _notifSub?.cancel();
          _notifSub = null;
        }
      });

      print(' Notifications initialization (auth watcher) set up');
    } catch (e) {
      print(' Error initializing notification auth watcher: $e');
    }
  }

  /// Purpose: Listens to the `notifications` Firestore collection and triggers local UI snackbars for high-priority alerts.
  /// Inputs: None. (Relies on the authenticated UID).
  /// Outputs: Modifies the [_notifSub] subscription.
  void _attachNotificationListener() {
    try {
      // 1. Guard clause: Ensure we don't accidentally create multiple overlapping stream listeners.
      if (_notifSub != null) return;

      final service = NotificationService();
      // 2. Fetch the current user ID securely.
      final uid = FirebaseAuth.instance.currentUser?.uid ?? '';
      
      // 3. Subscribe to the real-time Firebase stream.
      _notifSub = service.getNotificationsStream().listen((snapshot) {
        // 4. Filter the incoming documents strictly to the logged-in user as an extra security/data-integrity measure.
        final docs = uid.isNotEmpty
            ? snapshot.docs.where((d) {
                final data = d.data() as Map<String, dynamic>?;
                return data != null && (data['userId'] == uid || data['uid'] == uid);
              }).toList()
            : snapshot.docs;
            
        if (docs.isNotEmpty) {
          // 5. Extract the most recent notification payload from the top of the sorted stream.
          final latestData = docs.first.data() as Map<String, dynamic>?;
          if (latestData != null) {
            final title = latestData['title'] ?? 'Notification';
            final priority = (latestData['priority'] ?? 'normal').toString().toLowerCase();
            final isRead = latestData['isRead'] ?? false;
            
            // 6. Logic gate: Only trigger the invasive UI snackbar if the alert is both Unread AND High-Priority.
            if (!isRead && priority == 'high') {
              print(' New high-priority notification: $title');
              // 7. Delay the snackbar render until after the current layout frame completes to avoid "build during build" exceptions.
              WidgetsBinding.instance.addPostFrameCallback((_) => _showNotificationSnackbar(title));
            }
          }
        }
      }, onError: (error) {
        print(' Notification stream error: $error');
      });
    } catch (e) {
      print(' Failed to attach notification listener: $e');
    }
  }

  /// Purpose: Renders a global green banner at the bottom of the screen.
  /// Inputs: [title] - The alert message text.
  /// Outputs: Mutates the global ScaffoldMessenger UI overlay.
  void _showNotificationSnackbar(String title) {
    // 1. Access the global context via the statically held navigatorKey.
    final context = navigatorKey.currentContext;
    if (context != null) {
      // 2. Push the UI snackbar into the view hierarchy.
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(' $title'),
          backgroundColor: Colors.green.shade700,
          duration: const Duration(seconds: 4),
        ),
      );
    }
  }

  /// Purpose: Public API to change the app's visual theme dynamically.
  /// Inputs: [theme] - A human readable string ('Light Mode', 'Dark Mode').
  /// Outputs: Rebuilds the root widget and saves to SharedPreferences.
  void setTheme(String theme) {
    // 1. Update the state variable immediately to trigger UI rebuild.
    setState(() {
      _themeMode = _stringToThemeMode(theme);
    });
    // 2. Asynchronously commit the new preference to disk.
    SharedPreferences.getInstance().then((prefs) => prefs.setString('ui_theme', theme));
  }

  /// Purpose: Helper function to map UI strings to Flutter enums.
  /// Inputs: [theme] - String selection from Settings UI.
  /// Outputs: Returns the native [ThemeMode] enum.
  ThemeMode _stringToThemeMode(String theme) {
    switch (theme) {
      case 'Light Mode':
        return ThemeMode.light;
      case 'Dark Mode':
        return ThemeMode.dark;
      case 'Auto Mode':
      default:
        // 1. Fallback to reading the host OS's system preferences.
        return ThemeMode.system;
    }
  }

  @override
  void dispose() {
    _localizationProvider.dispose();
    _authSub?.cancel();
    _notifSub?.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      navigatorKey: navigatorKey,
      title: 'Smart Kisan',
      debugShowCheckedModeBanner: false,
      localizationsDelegates: context.localizationDelegates,
      supportedLocales: context.supportedLocales,
      locale: context.locale,
      themeMode: _themeMode,
      theme: ThemeData(
        brightness: Brightness.light,
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFF2C7C48),
          brightness: Brightness.light,
        ),
        fontFamily: 'Roboto',
        textTheme: const TextTheme(
          displayLarge: TextStyle(fontSize: 32, fontWeight: FontWeight.bold, color: const Color(0xFF101727)),
          displayMedium: TextStyle(fontSize: 28, fontWeight: FontWeight.bold, color: const Color(0xFF101727)),
          displaySmall: TextStyle(fontSize: 24, fontWeight: FontWeight.bold, color: const Color(0xFF101727)),
          headlineLarge: TextStyle(fontSize: 24, fontWeight: FontWeight.w600, color: const Color(0xFF101727)),
          headlineMedium: TextStyle(fontSize: 20, fontWeight: FontWeight.w600, color: const Color(0xFF101727)),
          headlineSmall: TextStyle(fontSize: 16, fontWeight: FontWeight.w600, color: const Color(0xFF495565)),
          titleLarge: TextStyle(fontSize: 16, fontWeight: FontWeight.w500, color: const Color(0xFF101727)),
          titleMedium: TextStyle(fontSize: 14, fontWeight: FontWeight.w500, color: const Color(0xFF495565)),
          titleSmall: TextStyle(fontSize: 12, fontWeight: FontWeight.w500, color: const Color(0xFF495565)),
          bodyLarge: TextStyle(fontSize: 16, fontWeight: FontWeight.w400, color: Color(0xFF354152)),
          bodyMedium: TextStyle(fontSize: 14, fontWeight: FontWeight.w400, color: const Color(0xFF495565)),
          bodySmall: TextStyle(fontSize: 12, fontWeight: FontWeight.w400, color: const Color(0xFF495565)),
          labelLarge: TextStyle(fontSize: 14, fontWeight: FontWeight.w500, color: const Color(0xFF00C950)),
          labelMedium: TextStyle(fontSize: 12, fontWeight: FontWeight.w500, color: const Color(0xFF00C950)),
          labelSmall: TextStyle(fontSize: 11, fontWeight: FontWeight.w500, color: const Color(0xFF00C950)),
        ),
        appBarTheme: const AppBarTheme(
          
          elevation: 0,
          centerTitle: false,
        ),
        scaffoldBackgroundColor: const Color(0xFFF9FAFB),
        cardColor: Colors.white,
      ),
      darkTheme: ThemeData(
        brightness: Brightness.dark,
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFF2C7C48),
          brightness: Brightness.dark,
        ),
        fontFamily: 'Roboto',
        textTheme: const TextTheme(
          displayLarge: TextStyle(fontSize: 32, fontWeight: FontWeight.bold, color: Color(0xFFF9FAFB)),
          displayMedium: TextStyle(fontSize: 28, fontWeight: FontWeight.bold, color: Color(0xFFF9FAFB)),
          displaySmall: TextStyle(fontSize: 24, fontWeight: FontWeight.bold, color: Color(0xFFF9FAFB)),
          headlineLarge: TextStyle(fontSize: 24, fontWeight: FontWeight.w600, color: Color(0xFFF9FAFB)),
          headlineMedium: TextStyle(fontSize: 20, fontWeight: FontWeight.w600, color: Color(0xFFF9FAFB)),
          headlineSmall: TextStyle(fontSize: 16, fontWeight: FontWeight.w600, color: Color(0xFFD1D5DC)),
          titleLarge: TextStyle(fontSize: 16, fontWeight: FontWeight.w500, color: Color(0xFFF9FAFB)),
          titleMedium: TextStyle(fontSize: 14, fontWeight: FontWeight.w500, color: Color(0xFFD1D5DC)),
          titleSmall: TextStyle(fontSize: 12, fontWeight: FontWeight.w500, color: Color(0xFFD1D5DC)),
          bodyLarge: TextStyle(fontSize: 16, fontWeight: FontWeight.w400, color: Color(0xFFE5E7EB)),
          bodyMedium: TextStyle(fontSize: 14, fontWeight: FontWeight.w400, color: Color(0xFFD1D5DC)),
          bodySmall: TextStyle(fontSize: 12, fontWeight: FontWeight.w400, color: Color(0xFFD1D5DC)),
          labelLarge: TextStyle(fontSize: 14, fontWeight: FontWeight.w500, color: const Color(0xFF00C950)),
          labelMedium: TextStyle(fontSize: 12, fontWeight: FontWeight.w500, color: const Color(0xFF00C950)),
          labelSmall: TextStyle(fontSize: 11, fontWeight: FontWeight.w500, color: const Color(0xFF00C950)),
        ),
        appBarTheme: const AppBarTheme(
          
          elevation: 0,
          centerTitle: false,
        ),
        scaffoldBackgroundColor: const Color(0xFF121212),
        cardColor: const Color(0xFF1F1F1F),

      ),
      initialRoute: '/',
      routes: {
        '/': (context) => const WelcomeScreen(),
        '/login': (context) => const LoginScreen(),
        '/home': (context) => const HomePage(
          isNewUser: false,
          userName: 'Farmer',
        ),
      },
    );
  }
}